### ISSUE TITLE
Web Identity vs Windows Identity

### ISSUE THREAD

**Issue by Saquibadil** [MohammadYounes/OWIN-MixedAuth#10]
How do I know what Authentication mode is used to authenticate a user. 
What I am trying to do is hide "Log Off" link for the users that are logged in using Windows Authentication. Because the Log Off is logging them back in since they are in network.

Request.IsAuthenticated is true for both Windows and Web.
I tried HttpContext.Current.Request.LogonUserIdentity.IsAuthenticated - which is also true for both windows and web. 

Is there any property that would be false for Web and true for Windows?

Thanks

**Comment by MohammadYounes** [comment]
Short answer:

No.

Long answer:

The windows authentication is just an entry point, once you get authenticated, the external identity will be [replaced by a local identity](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L335).

The log off link will still be required to log the user out. For example, a user logs in using windows identity then decides to switch to another local user.

Browsers will cache the windows credentials and use them for subsequent windows authentication requests, no prompt will be displayed asking for user credentials (Even if your internet settings were set to prompt for username and password).  So switching to another windows user requires invalidating the browser credentials cache (may be this could help  http://signinas.codeplex.com/)
