### ISSUE TITLE
Always redirect to login

### ISSUE THREAD

**Issue by b0bi79** [MohammadYounes/OWIN-MixedAuth#100]
I am trying to implement OWIN-MixedAuth in my MVC project, but I have a problem. I do everything by the example of the MVC application from the repository.
I click the Windows button on the Login page, but get redirects to the Login page again. In debug mode, I see that the login was successful, but why the Login page reappears? What could be the reason, maybe you came across this?

**Comment by MohammadYounes** [comment]
@b0bi79 I believe there is something missing, Do you face the same issue when running the provided examples ? Can you share your project code ?

**Comment by b0bi79** [comment]
Sorry, I figured it out. In fact, everything works. Just when I login with the domain name, a new user was created, which did not have rights. He was authenticated, but was not authorized, so I went redirect to the login page. Can you tell me how best to implement the output of the message that there is no rights, instead of redirecting to the login page?

**Comment by MohammadYounes** [comment]
@b0bi79 You need a custom authorize attribute, check this [article](https://www.red-gate.com/simple-talk/dotnet/asp-net/thoughts-on-asp-net-mvc-authorization-and-security), mainly the section titled [Not Authorized or Just Not Logged In?
](https://www.red-gate.com/simple-talk/dotnet/asp-net/thoughts-on-asp-net-mvc-authorization-and-security/#crayon-5c6d80465e122785536483)

**Comment by b0bi79** [comment]
Thanks
