### ISSUE TITLE
Wandering error 401.2

### ISSUE THREAD

**Issue by b0bi79** [MohammadYounes/OWIN-MixedAuth#101]
In my project, I made two authorization modes: by login/password and the Windows button. When I login by the Windows button, everything works well and there is no problem for a while. I have an auto-update every 10 minutes on the page `<meta http-equiv="refresh" content="600">`. After indefinite time, the page is loaded with the status 401.2 and the address MixedAuth?State=xxx.
I stopped execution at MixedAuthProvider.OnGetLogonUserIdentity and found out that sometimes my domain token is not authorized.
Here are the WindowsIdentity properties for successful and failure authorization.

Bad | Good
-- | --
{System.Security.Principal.WindowsIdentity} | {System.Security.Principal.WindowsIdentity}
**AuthenticationType: ""** | **AuthenticationType:   "Negotiate"**
**ImpersonationLevel: Delegation** | **ImpersonationLevel:   Impersonation**
IsAnonymous: false | IsAnonymous: false
**IsAuthenticated: false** | **IsAuthenticated: true**
IsGuest: false | IsGuest: false
IsSystem: false | IsSystem: false
Name: "IVOIN\\a.rozhkov" | Name:   "IVOIN\\a.rozhkov"
Owner: {S-1-5-21-542926684-345969227-1013978972-7456} | Owner:   {S-1-5-21-542926684-345969227-1013978972-7456}
Token: 2788 | Token: 3044
User: {S-1-5-21-542926684-345969227-1013978972-7456} | User:   {S-1-5-21-542926684-345969227-1013978972-7456}
UserClaims: Count = 27 | UserClaims: Count = 27

**Comment by b0bi79** [comment]
I noticed that on a working server on IIS, if login fails, the username looks like this "NT AUTHORITY\IUSR"

**Comment by MohammadYounes** [comment]
Not sure what would cause such behavior, but most probably this is IIS impersonating anonymous user account "NT AUTHORITY\IUSR". 

What are the application pool settings ? Does this happen under all browsers ?

**Comment by b0bi79** [comment]
Hmm, strange. Now I studied the situation deeper. The problem is reproduced only on my computer on the Chrome browser version 65.
In addition, in the first message I did not correctly indicate the error code. The Chrome page displays the following text:
```
The page is not available
If the problem persists, contact the site owner.
HTTP ERROR 401
```
But Developer Tools shows the last query as follows:
```
REQUEST
Request URL: http://10.99.109.203/AlphaBoard/MixedAuth?state=Wuu0XxjRY5lkzgtqKY9VlV9Y3JVaUbNHr1mg2tvmhX9mIjxCtdaZoqjjZy7Be6okU37im1qZRve5ml-5pTpYImsnvV5t-gpiQcfbvXkWaaJwJVyTV_UXFnKByx8DomtsyG9bHwiTxKZAh6DZO0IMX27ClrcFdsAXCJdrF8aAtJF4i_-pkt_D4Bn1wrJNStgI
Request Method: GET
Remote Address: 10.99.109.203:80
Referrer Policy: no-referrer-when-downgrade
Cookie: __RequestVerificationToken_L0FscGhhQm9hcmQ1=P7VV7CgzPLAIi-tJwVxcoCT4DDZp-z7uB6ADGYq-JKea5cE46nzW-ik9v0X-wqpXIvc9PouCJQN9WPcWLJUvTL5ypgbOMKucVpdO4ck72oA1; ASP.NET_SessionId=zttcke2tcyho4e0jhds2beyi
Host: 10.99.109.203
Referer: http://10.99.109.203/AlphaBoard/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

RESPONSE
Status Code: 302 Found
Cache-Control: no-cache
Content-Length: 0
Date: Mon, 03 Jun 2019 10:00:11 GMT
Expires: -1
Location: /AlphaBoard/Account/ExternalLoginCallback?ReturnUrl=%2FAlphaBoard%2F
Persistent-Auth: true
Pragma: no-cache
Server: Microsoft-IIS/7.5
Set-Cookie: .AspNet.ExternalCookie=d8vO4DKAq_0jrqDGnXB9v_GwnOkxZJQh0TC5VZ16e9l3dKgn7Mz2O64MyWxlPLRm1aBEWkkQfENGOwvpwEpTXS8YsB-rarJtnRKSYOM5JeWKfYTK8942z7NEEMe5lbEEihh-gekDHOpx3JupHN-yAdNQoUy4VR8s3XZJw2QsjlDl5-x4WnUUYC4Glg5JzUhrXSQ5-jwTrsLeP0J30ZHlK3OYODcZsTxETEPo_XAhM-uPEt_jUNTuR74YokXi5f_gaR1xDwo2Xx-WbhwLPfGEx73WEFZPHoehLLCICs6Jqt3r_quZQVIsBTxIOZcUdQB1LcVVdWb5fcz1nGlnwt8Pqp6JP5bpK1p_ULacAJSWmI0cDSgSkDsas-fzSk23Tr0tYgRAM7M5tpl_ab2fCVvK5fM2yZXXAFemyd5TKZBrZSaKGvOQmCOqxi28fYgJouIs2pvhsNpQSYoMFa1bFRUc5TnTp2elqlqSh8JQ63aLE37-J5KhcckoCjLCR9pgDsl5rlXjz9Acs3_-LbLMm-p3YeaXm91YPniob06gmgLAKMuP6iI6BIoFxH8CcwXqJEy_gvHzr0I_OT0SteSvO7Na0ALfIwUaqYQxAB7Upm8_J0E-E4mxjN8qAmNZwEvybhBA7oaoBf7EiPNm_o9hkEjX2YNT7qWDhQJxE6XQfBDLejXUTDOGQ71l47cmfL5CcP1ku1sYtRhpyBEOnMk3rykZ7ipTtl1gIgwkskyV3WByHQ7HYW9C0GkAHAw0pyu6xxhc; path=/; HttpOnly
X-Powered-By: ASP.NET
```
Apparently this is a browser issue. It should be redirected to `/AlphaBoard/Account/ExternalLoginCallback`, but it is not.

Do you know such problems?

**Comment by MohammadYounes** [comment]
Nope, I never faced such issue.

**Comment by b0bi79** [comment]
The issue was solved by updating the browser.
