### ISSUE TITLE
CORS Headers not exist with 401 Authentication Challenge Response from MixedAuthHandler

### ISSUE THREAD

**Issue by serkanz** [MohammadYounes/OWIN-MixedAuth#102]
Hi, 

I'm planning to use MixedAuth module in my project. Project is hosted on IIS with Owin and has MVC and Webapi endpoints. End users will use **/api/Token** (GET) api to access resource which requires authentication. I want my user to redirect to **/Account/Login** (form based authentication) view when they come from an external IP block, and **/Account/ExternalLogin** view when come from internal network (Windows machines).

Users will call my api from other sites via browser and javascript call. So I enabled Owin CORS on my app. Everything works pretty good when I call with form based authentication scenario, **/api/Token** redirects to form based login page and user logs in and get response from api endpoint. However when **/Account/ExternalLogin** view is called and MixedAuth module makes a 401 challenge, response lacks CORS headers so end user cannot continue. Is there a way to add CORS headers to  **/MixedAuth?state=W9vFl2hacdGKoclIQ_1iV7zI1RK8TEgVScwei04PczHBI6ER8zsz9....** path also?

Kind regards

**Comment by MohammadYounes** [comment]
@serkanz Is this the same case as  #62 ?

**Comment by serkanz** [comment]
@MohammadYounes thanks for your quick response. I called useCors method after calling useMixedAuth. So When I replaced the order it worked as it's expected. I'm closing the issue now.
