### ISSUE TITLE
Server Error in '/' Application after login in sample project (CREATE DATABASE failed)

### ISSUE THREAD

**Issue by chtenb** [MohammadYounes/OWIN-MixedAuth#103]
I compile and run the sample MVC project following the README.md.
After clicking `Login` -> `Windows` I get the following error
![image](https://user-images.githubusercontent.com/1030961/74722937-05f8e580-523a-11ea-80fa-5f0ca6b0fae9.png)

**Comment by MohammadYounes** [comment]
@Chiel92 This means it can't create the database, either install LocalDb or update the connection string to point to your SQL Server.

**Comment by chtenb** [comment]
Thank you
