### ISSUE TITLE
Replace HTTP Error 401.2 - Unauthorized default error page with custom error page?

### ISSUE THREAD

**Issue by chtenb** [MohammadYounes/OWIN-MixedAuth#104]
When starting the MVC sample project with firefox, clicking on the `Windows` login method, I get the following popup: 
![image](https://user-images.githubusercontent.com/1030961/75777358-22c30c00-5d56-11ea-8751-aebcf6a08688.png)

This is expected, because firefox does this by default, and needs additional configuration changes to prevent this from happening, so that's okay. When pressing the cancel button, I land on a HTTP Error 401.2 - Unauthorized error page: 
![image](https://user-images.githubusercontent.com/1030961/75777535-70d80f80-5d56-11ea-861c-7d3f1031fdce.png)

This is expected as well. However my question is, how can I customize this error page? I don't want these IIS error pages to leak to the end user.

I tried adding the following to the web.config:
```xml
        <httpErrors errorMode="Custom" existingResponse="Replace">
            <remove statusCode="401" subStatusCode="-1" />
            <error statusCode="401" path="/Account/MyCustomErrorPage" responseMode="ExecuteURL" />
        </httpErrors>        
```

However, this breaks the Windows login method completely, as it will always redirect to MyCustomErrorPage now.

How can I customize the error page?

**Comment by MohammadYounes** [comment]
@Chiel92 I think you can send your own response in **Global.asax** `EndRequest` event.

Add the below to Global.asax consturctor before `this.RegisterMixedAuth();`

```c#
this.EndRequest += (object sender, EventArgs e) =>
{
    if (this.Context.Response.StatusCode == 418)
    {
        this.Context.Response.Clear();
        this.Context.Response.Write("user pressed cancel");

    }
    else if (this.Context.Response.StatusCode == 401)
    {
        this.Context.Response.Clear();
        this.Context.Response.Write("login failed.");
    }
};
```

**Comment by chtenb** [comment]
Thanks for your response. This indeed seems to work. However, would it also be possible to just return to the login screen with an error message, instead of writing a plain html string?

**Comment by MohammadYounes** [comment]
You could return a content that redirects to the login page:

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <!-- redirect to normal login page -->
    <meta http-equiv="refresh" content="0;URL='/Account/Login'" />
</head>
<body>
    Invalid credentials, redirecting ...
</body>
</html>
```
