### ISSUE TITLE
Suppress Windows Authentication Dialog 

### ISSUE THREAD

**Issue by baresp** [MohammadYounes/OWIN-MixedAuth#105]
Is it possible to suppress Windows Authentication Dialog when autentication fail (user does not exist) and redirect to custom autentication form (cookie autentication) ?

**Comment by MohammadYounes** [comment]
Did you check #104 ? Is this the same ?

**Comment by Madhu-Patty** [comment]
@MohammadYounes 

I tried using #104 and i open one #55. 

I have my code like this

public static void RegisterWindowsAuthentication(this MvcApplication app)
        {
            app.EndRequest += (object sender, EventArgs e) =>
            {
                if (app.Context.Response.StatusCode == 418)
                {
                    app.Context.Response.Clear();
                    app.Context.Response.Write("user pressed cancel");

                }
                else if (app.Context.Response.StatusCode == 401)
                {
                    app.Context.Response.Clear();
                    app.Context.Response.Write("login failed.");
                }
            };


Global.asax has 
   public MvcApplication()
        {
            this.RegisterWindowsAuthentication();
        }


Web.config has
  <system.webServer>
    <httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="401" subStatusCode="-1" />
      <error statusCode="401" path="/Account/Authentication" responseMode="ExecuteURL" />
    </httpErrors>
</system.webServer>

Always getting 401 and always redirecting to custom error page. Can you help me on this?

**Comment by baresp** [comment]
> Did you check #104 ? Is this the same ?

No, I need suppress login dialog on server side (without reconfigure browser)
 
GET /TestMixAuth/MixedAuth?state=a5EG94shpmPiI5WQbrD1I_DHH...
server response HTTP/1.1 401 Unauthorized
When user does not exist (from different domain in my test) then browser show login dialog.

But if user exist (maybe because in the same domain ) browser send next request with auth. header and continue with authentication
GET /TestMixAuth/MixedAuth?state=a5EG94shpmPiI5WQbrD1I_DH...
WWW-Authenticate: Negotiate oYH0MIHxoAMKAQGhDAYKKwYBB....

I do not know how to distinguish these two requests, so that the first case does not display a dialog but was redirected to login and finished login in second case.

Have you any idea ?

**Comment by MohammadYounes** [comment]
@baresp 
Suppressing the dialog means automatic login with current credentials, which is a client configuration that depends on **Security Settings/User Authentication** of the current site zone:

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)
