### ISSUE TITLE
Updating the Claims 

### ISSUE THREAD

**Issue by thak123** [MohammadYounes/OWIN-MixedAuth#11]
I am using this owin mixed windows & its working fine .

how can u update  a claim ?
```C#
var identity = new ClaimsIdentity(_authenticationManager.User.Identity);

identity.RemoveClaim(identity.FindFirst(ClaimTypes.UserData));
identity.AddClaim(new Claim(ClaimTypes.UserData, domainId.ToString()));

// Save new claim in cookie
_authenticationManager.AuthenticationResponseGrant = new AuthenticationResponseGrant(new ClaimsPrincipal(identity), new AuthenticationProperties { IsPersistent = true });
```
I m getting error 
The Claim '' was not able to be removed. It is either not part of this Identity or it is a claim that is owned by the Principal that contains this Identity. For example, the Principal will own the claim when creating a GenericPrincipal with roles. The roles will be exposed through the Identity that is passed in the constructor, but not actually owned by the Identity. Similar logic exists for a RolePrincipal.

**Comment by MohammadYounes** [comment]
Its hard to tell from the code you provided, have you tried updating the claim instead of replacing it! can share a sample application ?

**Comment by thak123** [comment]
// Get User
                var user = await _userService.GetUser(userId);

                if (user.Domains.Count > 0)
                {
                    var domain = user.Domains.Where(r => r.DomainID == domainId).First();
                    if (domain != null)
                    {
                        var identity = new ClaimsIdentity(_authenticationManager.User.Identity);

                        identity.RemoveClaim(identity.FindFirst(ClaimTypes.UserData));
                        identity.AddClaim(new Claim(ClaimTypes.UserData, domainId.ToString()));

                        // Save new claim in cookie
                        _authenticationManager.AuthenticationResponseGrant = new AuthenticationResponseGrant
                            (new ClaimsPrincipal(identity), new AuthenticationProperties { IsPersistent = true });

                        // Save new domain on User
                        await _userService.SetCurrentDomain(user.UserID, domainId);
                        
                        //Set the new selected Domain
                        _sessionService.Set(SessionKey.Domain, domain);
                    }
                }

**Comment by thak123** [comment]
updating the claim .How that can be done ?

**Comment by MohammadYounes** [comment]
I don't have a sample app at my disposal at the moment, it will be super helpful if you could put a complete sample that I can debug.

Based on the error you described and the code sample your provided, you may try the following
 (NOT TESTED!)
```c#
// Get User
var user = await _userService.GetUser(userId);

if (user.Domains.Count > 0)
{
  var domain = user.Domains.Where(r => r.DomainID == domainId).First();
  if (domain != null)
  {
    ClaimsPrincipal cp = _authenticationManager.User;
    foreach (var  identity in cp.Identities)
    {
      Claim claim = identity.FindFirst(ClaimTypes.UserData);
      if(claim!=null)
      {
        identity.RemoveClaim(claim);
        identity.AddClaim(new Claim(ClaimTypes.UserData, domainId.ToString()));
      }
    }

    // Save new claim in cookie
    _authenticationManager.AuthenticationResponseGrant = new AuthenticationResponseGrant(cp, new AuthenticationProperties { IsPersistent = true });

    // Save new domain on User
    await _userService.SetCurrentDomain(user.UserID, domainId);
                        
    //Set the new selected Domain
    _sessionService.Set(SessionKey.Domain, domain);
  }
}
```

**Comment by thak123** [comment]
Thanks very much.It worked Like a charm

**Comment by MohammadYounes** [comment]
Awesome :+1: 

Thanks for the feedback!
