### ISSUE TITLE
Consider changing how you get logonUserIdentity

### ISSUE THREAD

**Issue by sania13** [MohammadYounes/OWIN-MixedAuth#13]
I suggest you to change how you get your logonUserIdentity’. It is only available in ‘PostAuthenticate’ OWIN pipeline stage events. If you protect your resources with OAuth2/Open ID connect Identity provider you would be running in ‘Authenticate’ event and ‘logonUserIdentity’ is not  available (((System.Web.HttpContextBase)Request.Environment["System.Web.HttpContextBase"]).Request.LogonUserIdentity) , but if you change to (Response.Context).Authentication).User it would work in both OWIN pipeline stage events.  

I implemented something similar and it is working.

**Comment by MohammadYounes** [comment]
Not sure how its working for you? as I'm interested in getting the [`WindowsIdentity`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/Provider/IMixedAuthProvider.cs#L31) !

**Comment by MohammadYounes** [comment]
[Usage](https://github.com/MohammadYounes/OWIN-MixedAuth#usage) Step 3
>3 . Use `MixedAuth` in **Startup.Auth.cs**
>  ```C#
>  //Enable Mixed Authentication
>  //As we are using LogonUserIdentity, its required to run in PipelineStage.PostAuthenticate
>  //Register this after any middleware that uses stage marker PipelineStage.Authenticate
>
>  app.UseMixedAuth(cookieOptions);
>  ```
>  **Important!** MixedAuth is required to run in `PipelineStage.PostAuthenticate`, make sure the use statement is after any other middleware that uses `PipelineStage.Authenticate`. See [OWIN Middleware in the IIS integrated pipeline](http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline).
 

As long as you configure MixedAuth after any provider that uses  `PipelineStage.Authenticate`, you'll run in `PipelineStage.PostAuthenticate`.
