### ISSUE TITLE
Authentication - Windows to Read/Write

### ISSUE THREAD

**Issue by Saquibadil** [MohammadYounes/OWIN-MixedAuth#14]
This setting is done on the server node in IIS. (Feature Delegation)
Well, at my client side there are lot of other applications in one server. Changing this setting on server node for my application might affect other applications. How can I make this setting for only my application?

**Comment by MohammadYounes** [comment]
If you want to configure delegation for just one site, use the Custom Site Delegation as described [here](http://www.iis.net/learn/manage/managing-your-configuration-settings/an-overview-of-feature-delegation-in-iis)

![Custom Delegation](http://i1.iis.net/media/7179269/an-overview-of-feature-delegation-in-iis-155-An%20Overview%20of%20Feature%20Delegation%20in%20IIS%207.0%20-%20Figure%204.jpg?cdn_id=2015-04-07-001)
