### ISSUE TITLE
LogOff issue?

### ISSUE THREAD

**Issue by lpawlak** [MohammadYounes/OWIN-MixedAuth#15]
Firefox/ MVC 5 Project
User is authorized by external (Windows) login. After execute LogOff and don't close browser windows when click Windows login don't have to enter login and password. so if many user uses the same PC, and don't close browser, can log to other account!
I have following action:
```
[HttpPost]
[ValidateAntiForgeryToken]
public ActionResult LogOff()
{
	AuthenticationManager.SignOut();
	if (Request.Cookies[".AspNet.ApplicationCookie"] != null)
	{
		var c = new HttpCookie(".AspNet.ApplicationCookie");
		c.Expires = DateTime.Now.AddDays(-1);
		Response.Cookies.Add(c);
	}            
	return RedirectToAction("Index", "Home");
}
```
Please help.

**Comment by MohammadYounes** [comment]
This behavior is by default. Browsers will cache the windows credentials and use them for subsequent windows authentication requests, no prompt will be displayed asking for user credentials (Even if your internet settings were set to prompt for username and password).  You need to either close the browser or invalidate the browser credentials cache.

The log off link will still be required to log the user out. For example, a user logs in using windows identity then decides to switch to another local user.
