### ISSUE TITLE
ExternalSignInAsync fails

### ISSUE THREAD

**Issue by Saquibadil** [MohammadYounes/OWIN-MixedAuth#16]
So, I am trying to login using Windows authentication, over the internet.

First I connected to Domain, using PrincipalContext, like this
```C#
using (var context = new PrincipalContext(ContextType.Domain, "domain_name"))
{
     UserPrincipal userPrincipal = UserPrincipal.FindByIdentity(context, userName);               
     var valid = context.ValidateCredentials(userName, password);
     if (valid)
     {
          var loginInfo = new ExternalLoginInfo
          {
               DefaultUserName = userPrincipal.GivenName + " " + userPrincipal.Surname,
               Login = new UserLoginInfo("Windows", userPrincipal.Sid.ToString())
          };
         signInStatus = await ExternalSignInAsync(loginInfo, isPersistent);
     }
}
```
userPrincipal.Sid is correct - validated it.

The thing is this code was working couple days ago, when I demoed. But all of a sudden it stopped working and I have no idea. 

I checked all my configuration changes. 

applicationhost file is correct,
```xml
<section name="windowsAuthentication" overrideModeDefault="Allow" />
```
Authentication - Windows is set to Read/Write in my IIS delegation setting.

And I checked all the code, everything is as it should be.

It stopped working in QA environment, which has not been deployed since few days and it was working fine yesterday in QA.
It also stopped working in Local. 

What do you think might be wrong. 

Update 1:

I even tried 
```C#
var user = await UserManager.FindAsync(new UserLoginInfo("Windows", "my sid"));
```
But the user is null.

**Comment by MohammadYounes** [comment]
Based on your last update, seems the problem is with finding the user using the external login info. Are you using a custom user manager or asp.net default ?

**Comment by Saquibadil** [comment]
I am using asp.net default user manager. 

Other users are facing similar issues with using external logins... Just in case it might ring any bell for you...

http://stackoverflow.com/questions/19453293/asp-net-mvc-5-vs2013-final-facebook-login-with-owin-fails-logininfo-is-null/21439834#21439834

http://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser/21234614#21234614

http://stackoverflow.com/questions/28215962/net-identity-2-0-facebook-externallogin-logininfo-returns-null

**Comment by MohammadYounes** [comment]
That's different from your case, `GetExternalLoginInfoAsync` reads the external cookie, In your case you are not doing that!

Also you state that a direct call to your user store `UserManager.FindAsync(new UserLoginInfo("Windows", "my sid"));` does not return the user!! 

Open your DB and check the `UserLogins` table and see if you can find a record matching the provided info 

| loginProvider | providerKey
| ----------------- | ------------------
| Windows | my sid

**Comment by Saquibadil** [comment]
Oh. That's my bad.

I want to login the windows user without storing it's record in UserLogins table, since we have a service that authenticates the user. 
The requirement I have is to login the user without creating a record in UserLogins, can I just do SignInAsync() by passing the user that doesn't exist in database?

Thank you very much!

**Comment by MohammadYounes** [comment]
No, if you are using the default asp.net UserManager. At least you must have some custom logic to map the windows user to a local user account and then call `SignInAsync` passing the local account.

**Comment by Saquibadil** [comment]
Do you know how it is possible to map windows user to a local user account, without creating a record in database. 

Thank you!

**Comment by MohammadYounes** [comment]
How do you register your windows users ?

**Comment by Saquibadil** [comment]
Windows users just like web users, enter their username and password when they login over the internet. Then we have a service that accepts username and password and tell us whether the user is valid. We don't do registration for windows users.

**Comment by MohammadYounes** [comment]
Since you don't do registration for windows users, then perhaps create dummy local accounts! 
```C#
string userName = string.Format("{0}@{1}", userName, domainName);
var user = await UserManager.FindByNameAsync(userName);
if(user == null){
  //first time login, create local account with no password.
  var result = await UserManager.CreateAsync(user);
  if (!result.Succeeded)
    throw new ApplicationException("Failed to create local account");                  
}
await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
```

**Comment by Saquibadil** [comment]
But does it not create a record in User table.
Can I just log the user in from code, without going to database.

**Comment by MohammadYounes** [comment]
You could do: 
```C#
string userName = string.Format("{0}@{1}", userName, domainName);
var user = new ApplicationUser { UserName = userName, Email = userName };
await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
```
But things will turn ugly in case any DB call is made by the `SignInManager`, for example checking if the user email or phone number are confirmed!

**Comment by Saquibadil** [comment]
Thanks for your reply MohammadYounes.

I tried implementing the above code but it is throwing an exception with a message. UserId is null

Is there anything I can do to skip this error.

**Comment by MohammadYounes** [comment]
Such exception is very much expected! You are trying to make a system that is based around user to work without one.
