### ISSUE TITLE
ApiController requests are unauthenticated

### ISSUE THREAD

**Issue by TrabacchinLuigi** [MohammadYounes/OWIN-MixedAuth#18]
i've installed this middleware with nuget on an MVC5 with controller AND ApiControllers
the default configuration for ApiController include those two lines that seems to prevent the authentication to work. Commenting them out seems to get things back to normality, but i wonder if this is a correct behaviour.

    // App_Start\WebApiConfig.cs
    
    // Web API configuration and services
    // Configure Web API to use only bearer token authentication.
    config.SuppressDefaultHostAuthentication();
    config.Filters.Add(new HostAuthenticationFilter(OAuthDefaults.AuthenticationType));

please note that, adding an ApiController later does not create those two lines, but creating a new project with both mvc and api does.

**Comment by MohammadYounes** [comment]
These are used to enable suppression of the host's default authentication, Forcing your Web API to use only bearer tokens for authentication.

This means you must first get an Access Token, then send an Authorization header with each API call `Authorization: Bearer imSXTs2OqSrGWzsFQhIXziFCO3rF...` 

You can find more details and a sample [here](http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api).
