### ISSUE TITLE
Error when running app with MixedAuth turned on

### ISSUE THREAD

**Issue by brianflynn** [MohammadYounes/OWIN-MixedAuth#20]
I'm running .net 4.5, MVC 5 and the latest Entity Framework version. When I enable MixedAuthentication, I get the following exception before it ever hits a single Controller. 

[NullReferenceException: Object reference not set to an instance of an object.]
   System.Web.PipelineStepManager.ResumeSteps(Exception error) +2324
   System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb) +215
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +287

**Comment by MohammadYounes** [comment]
Can you share a sample project, or use the source code and try debugging it ?

**Comment by brianflynn** [comment]
I appreciate the offer, but I got everything working. Thanks!

**Comment by MohammadYounes** [comment]
Would you care to share what was wrong? might help others in case they face a similar issue!

Thanks.

**Comment by brianflynn** [comment]
I blew away my solution and started over because I was having so many issues, and when I tried again, it worked. That being said, I believe it was because I had placed “this.RegisterMixedAuth();” in the “Application_Start()” instead of the MvcApplication constructor but I don’t know that for a fact.

**Comment by MohammadYounes** [comment]
Thanks for the feedback, very much appreciated!
