### ISSUE TITLE
Copyright and license

### ISSUE THREAD

**Issue by acctforrandomstuff** [MohammadYounes/OWIN-MixedAuth#21]
It seems large parts of your code are taken from the `Microsoft.Owin.Security` libraries with only minor edits, like renaming the namespace and class, e.g. `MohammadYounes.Owin.Security.MixedAuth/Provider/MixedAuthApplyRedirectContext.cs` is from `Microsoft.Owin.Security.Google/Provider/GoogleApplyRedirectContext.cs`.  Shouldn't you retain their copyright headers rather than replacing with your own?  Also, if I'm not mistaken the original code is licensed using the Apache license not MIT's.

**Comment by MohammadYounes** [comment]
Following the patterns used in building OWIN providers in Katana project does not mean the code is taken from there! For example: [OwinOAuthProviders](https://github.com/RockstarLabs/OwinOAuthProviders) which is licensed under MIT too.

**Comment by acctforrandomstuff** [comment]
I'm not a lawyer so maybe I'm misunderstanding the use of copyrights and licenses.  Are you saying the code in the Provider folder is not copyrightable because they are merely a patterns?  I looked at a few of the files in the RockstarLabs project that you linked and don't see that they claimed any copyright on that code.

**Comment by MohammadYounes** [comment]
Well, now I'm not sure if this is considered a copyright infringement or not! As for RockstarLabs, the copyright notice redirects you to [license.txt](https://github.com/RockstarLabs/OwinOAuthProviders/blob/master/license.txt).

**Comment by acctforrandomstuff** [comment]
Perhaps I shouldn't have used the word "taken" in my initial comment as I'm sure it was inadvertent.  I just wanted to point out that your copyright claims for some of this code might be somewhat questionable.  For example, compare these:

[GoogleAuthenticationProvider](https://github.com/yreynhout/katana-clone/blob/master/src/Microsoft.Owin.Security.Google/Provider/GoogleAuthenticationProvider.cs)
[MixedAuthProvider](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/Provider/MixedAuthProvider.cs)

[MicrosoftAccountAuthenticationOptions](https://github.com/yreynhout/katana-clone/blob/master/src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationOptions.cs)
[MixedAuthOptions](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthOptions.cs)

**Comment by MohammadYounes** [comment]
I'm aware of the similarities, as I tried to make it as much as possible similar to Katana, which makes it easier for developers to use/debug the MixedAuth middleware.

**Comment by acctforrandomstuff** [comment]
I don't see a problem with that.  But why the copyright claim?  If there's to be any copyright header on those files, the original ones should be there instead or at least in addition to yours.  The Apache License and Notice files should also be included.

**Comment by MohammadYounes** [comment]
> why the copyright claim?

Because I'm the author of these files.

>The Apache License and Notice files should also be included.

I don't think it's necessary.

May I ask why you are so concerned about this ?

**Comment by acctforrandomstuff** [comment]
> Because I'm the author of these files.

As far as I understand, "author" means "original creator", which doesn't appear to me to be the case, even the comments are exactly same.  Btw, you forgot to change the [`options`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/Provider/MixedAuthApplyRedirectContext.cs#L30) param in `MixedAuthApplyRedirectContext.cs`.

> I don't think it's necessary.
> May I ask why you are so concerned about this ?

Since you took the time to add your own copyright and license to these files and resistant to changing them, you obviously see value in copyrights.  So why not respect copyright claims of others?

**Comment by MohammadYounes** [comment]
I'm not resistant to change, and I don't deny using some code from katana project. But you still didn't answer my question!

**Comment by acctforrandomstuff** [comment]
Redirecting this issue to make it about me and my concerns is unhelpful and off-topic.  But if your curiosity must be satisfied, I'm concerned because I believe OSS is a sort of ecosystem which works best when we respect each other and our contributions.  And, part of that is not claiming authorship of someone else's work.

**Comment by MohammadYounes** [comment]
I appreciate your concern, and I didn't intend to take credit for someone else's work. I'm sorry it looks like that to you.

Will clear this up in the next update.

Thanks.

**Comment by MohammadYounes** [comment]
@acctforrandomstuff Sorry for being late on this, Is [this update](https://github.com/MohammadYounes/OWIN-MixedAuth/commit/82b787314e9decbeb9462da10e07fe49edfd6735) clear enough ?
