### ISSUE TITLE
401.2 : You are not authorized to view this page due to invalid authentication headers.

### ISSUE THREAD

**Issue by dotnetfreak** [MohammadYounes/OWIN-MixedAuth#22]
Mohammed,
Have you come across getting a 401.2 - Unauthorized "You are not authorized to view this page due to invalid authentication headers." exception before?

I have deployed to IIS on Server 2012. The AppPool is running Integrated mode.  I have unlocked the Feature Delegation settings to do with Authentication.  I have added the following in the web config.
```xml
<location path="MixedAuth">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
    </system.webServer>
  </location>
```
and yet I get the above error message when I click the windows option.  The URL when the error is displayed is .../MixedAuth?state=....

In ApplyResponseChallengeAsync the identity is NT AUTHORITY\IUSR:
AuthenticateCoreAsync never seems to get invoked.

I dont suppose you have any clues?  where i can look or add logging to?  

thanks.

**Comment by MohammadYounes** [comment]
Try enabling **Anonymous Authentication**!

**Comment by dotnetfreak** [comment]
The correct answer would be..."Try Installing Windows Authentication on the server".  Doh! Sorry.

**Comment by MohammadYounes** [comment]
:smile:
