### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DeHaynes** [MohammadYounes/OWIN-MixedAuth#23]
I tried setting your MixedAuth up in a Visual Studio 2013 MVC WebApplication.  I keep getting "Object reference not set to an instance of an object."  I decompiled your DLL and added it back in as a project to try and determine where the issue was at.  It keeps getting caught on the following line

			if (base.Response.StatusCode != 401)
			{
				return Task.FromResult<object>(null);
			}

in the ApplyResponseChallengeAsync method of the MixedAuthHandler class.
My stack trace looks like

System.Web.PipelineModuleStepContainer.GetStepArray(RequestNotification notification, Boolean isPostEvent) +22
   System.Web.PipelineStepManager.ResumeSteps(Exception error) +1324
   System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb) +95
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +186

**Comment by DeHaynes** [comment]
I downloaded the source-code and tried it.  I got the same results.

**Comment by DeHaynes** [comment]
I figured it out.  In the Global.asax.cs, I put the "this.RegisterMixedAuth();" inside of the "Application_Start" method instead of in the constructor.

**Comment by MohammadYounes** [comment]
Great!

Thanks for the feedback.
