### ISSUE TITLE
HTTP Error 418.0 The module does not recognize the error affected.

### ISSUE THREAD

**Issue by Klainer** [MohammadYounes/OWIN-MixedAuth#29]
Hello thanks for your code. I try implement it with ABP framework (http://www.aspnetboilerplate.com/), but when I try logIn by windows button, I got this error message:

HTTP Error 418.0 The module does not recognize the error affected.
Detailed Error Information:
Module	   ManagedPipelineHandler
Notification	   ExecuteRequestHandler
Handler	   Windows Login Handler
Error Code	   0x00000000

Where is problem? It is possible to work with ABP ? It is possible to make sample ? Many thanks !

**Comment by MohammadYounes** [comment]
Did you follow the [usage steps](https://github.com/MohammadYounes/OWIN-MixedAuth#usage) ?

Seems you didn't register it in **Global.asax**, please confirm!

**Comment by Klainer** [comment]
Ok works THANKS FOR QICK REPLY !, but not completly, I got another error: The provided anti-forgery token was meant for user "", but the current user is "MM-PC\Martin". on WindowsLoginHandler.cs    row: 119 BTW I used code from https://github.com/MohammadYounes/MVC5-MixedAuth .. It is possible to do sample with ABP framework ?

**Comment by Klainer** [comment]
Ok, thanks, clear cookies no work. Yes MVC5-MixedAuth, I´m sorry. I understand but if you find the time I will be very grateful!

**Comment by MohammadYounes** [comment]
Can you share a sample app with your modifications?

**Comment by MohammadYounes** [comment]
Closing this, Once you manage to put together a sample online, please open a new issue at [MVC5-MixedAuth](https://github.com/MohammadYounes/MVC5-MixedAuth).

Thanks!

**Comment by Klainer** [comment]
Hello, I prepared sample project with Owin Mixed auth. There is a link: https://mega.nz/#!6E0nHQ5Y!wN2ZR7j5s3cE2RdkYW-nIgeWoGwzjLZdj349S15Lt34

 I´m using ABP, login screen show windows auth icon. After click i got error:

[ArgumentNullException: Hodnota nemůže být NULL.
Název parametru: key]
   System.Collections.Generic.Dictionary`2.FindEntry(TKey key) +12209537
   System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) +16
   MohammadYounes.Owin.Security.MixedAuth.MixedAuthHandler.ReplaceCookie() in c:\Users\myounes\Documents\GitHub\OWIN-MixedAuth\src\MohammadYounes.Owin.Security.MixedAuth\MixedAuthHandler.cs:290
   MohammadYounes.Owin.Security.MixedAuth.MixedAuthHandler.ApplyResponseChallengeAsync() in c:\Users\myounes\Documents\GitHub\OWIN-MixedAuth\src\MohammadYounes.Owin.Security.MixedAuth\MixedAuthHandler.cs:195

After success login shoull be new Record in Abp.Users table. Thank you very much !

**Comment by MohammadYounes** [comment]
Thanks! Answered [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/30#issuecomment-158173793).
