### ISSUE TITLE
OWIN-MixedAuth with ABP - no work

### ISSUE THREAD

**Issue by Klainer** [MohammadYounes/OWIN-MixedAuth#30]
Hello, I prepared sample project with Owin Mixed auth. There is a link: https://mega.nz/#!6E0nHQ5Y!wN2ZR7j5s3cE2RdkYW-nIgeWoGwzjLZdj349S15Lt34

I´m using ABP, login screen show windows auth icon. After click i got error:

[ArgumentNullException: Hodnota nemůže být NULL.
Název parametru: key]
System.Collections.Generic.Dictionary2.FindEntry(TKey key) +12209537 System.Collections.Generic.Dictionary2.TryGetValue(TKey key, TValue& value) +16
MohammadYounes.Owin.Security.MixedAuth.MixedAuthHandler.ReplaceCookie() in c:\Users\myounes\Documents\GitHub\OWIN-MixedAuth\src\MohammadYounes.Owin.Security.MixedAuth\MixedAuthHandler.cs:290
MohammadYounes.Owin.Security.MixedAuth.MixedAuthHandler.ApplyResponseChallengeAsync() in c:\Users\myounes\Documents\GitHub\OWIN-MixedAuth\src\MohammadYounes.Owin.Security.MixedAuth\MixedAuthHandler.cs:195

After success login shoull be new Record in Abp.Users table. Thank you very much !

**Comment by MohammadYounes** [comment]
Hi, Thanks for the sample!

Your issue is due to using MixedAuth before other middlewares that uses `PipelineStage.Authenticate`, As mentioned in step 3 in the [Usage Section](https://github.com/MohammadYounes/OWIN-MixedAuth#usage):

>As we are using` LogonUserIdentity`, its required to run in `PipelineStage.PostAuthenticate`
>Register this after any middleware that uses stage marker `PipelineStage.Authenticate`

Update your Startup class as follows and you are good to go!

```C#
public void Configuration(IAppBuilder app)
{
    app.UseOAuthBearerAuthentication(AccountController.OAuthBearerOptions);

    var cookieOptions = new CookieAuthenticationOptions
    {
        AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
        LoginPath = new PathString("/Account/Login")
    };

    app.UseCookieAuthentication(cookieOptions);

    app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

    if (IsTrue("ExternalAuth.Facebook.IsEnabled"))
    {
        app.UseFacebookAuthentication(CreateFacebookAuthOptions());
    }

    if (IsTrue("ExternalAuth.Twitter.IsEnabled"))
    {
        app.UseTwitterAuthentication(CreateTwitterAuthOptions());
    }

    if (IsTrue("ExternalAuth.Google.IsEnabled"))
    {
        app.UseGoogleAuthentication(CreateGoogleAuthOptions());
    }

    app.UseMixedAuth(new MixedAuthOptions()
    {
        Provider = new MixedAuthProvider()
        {
            OnImportClaims = identity =>
            {
                List<Claim> claims = new List<Claim>();

                using (var principalContext = new PrincipalContext(ContextType.Domain))
                {
                    using (UserPrincipal userPrincipal = UserPrincipal.FindByIdentity(principalContext, identity.Name))
                    {
                        if (userPrincipal != null)
                        {
                            claims.Add(new Claim(ClaimTypes.Email, userPrincipal.EmailAddress ?? string.Empty));
                            claims.Add(new Claim(ClaimTypes.Surname, userPrincipal.Surname ?? string.Empty));
                            claims.Add(new Claim(ClaimTypes.GivenName, userPrincipal.GivenName ?? string.Empty));
                        }
                    }
                }
                return claims;
            }
        }

    }, cookieOptions);
}
```

**Comment by Klainer** [comment]
Thanks! But i get another error: HTTP Error 500.19 - Internal Server Error (problem with config):

Resource od configuration:
 50:         <authentication>
   51:           <windowsAuthentication enabled="true" />
   52:         </authentication>

I red your manual, in I update ISS Expres applicationhost.config file. 
```
            <sectionGroup name="security">
                <section name="access" overrideModeDefault="Deny" />
                <section name="applicationDependencies" overrideModeDefault="Deny" />
                <sectionGroup name="authentication">
                    <section name="anonymousAuthentication" overrideModeDefault="Deny" />
                    <section name="basicAuthentication" overrideModeDefault="Deny" />
                    <section name="clientCertificateMappingAuthentication" overrideModeDefault="Deny" />
                    <section name="digestAuthentication" overrideModeDefault="Deny" />
                    <section name="iisClientCertificateMappingAuthentication" overrideModeDefault="Deny" />
            <sectionGroup name="security">
                <section name="access" overrideModeDefault="Deny" />
                <section name="applicationDependencies" overrideModeDefault="Deny" />
                <sectionGroup name="authentication">
                    <section name="anonymousAuthentication" overrideModeDefault="Deny" />
                    <section name="basicAuthentication" overrideModeDefault="Deny" />
                    <section name="clientCertificateMappingAuthentication" overrideModeDefault="Deny" />
                    <section name="digestAuthentication" overrideModeDefault="Deny" />
                    <section name="iisClientCertificateMappingAuthentication" overrideModeDefault="Deny" />
                    <section name="windowsAuthentication" overrideModeDefault="Allow" />
                </sectionGroup>

```

Also is possible tu be USER logged automaticly by windows logOn ? THANKS!

**Comment by MohammadYounes** [comment]
Are you using VS2015 ? 
If yes, updating the one inside **$:\Users\{username}\Documents\IISExpress\config** won't do, you need to update the one located at **$(SolutionDir)\.vs\config**.

Thanks

**Comment by MohammadYounes** [comment]
For Auto Windows login, follow the steps mentioned [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443).

**Comment by Klainer** [comment]
Works, but last problem is that, when I logout and signIn by form it cause redirection LOOP ERR_TOO_MANY_REDIRECTS... So i canot login.

**Comment by MohammadYounes** [comment]
I tested this and I got no such error! Did you enable anonymous authentication ?

**Comment by Klainer** [comment]
Ok, I explain it more. I setup ato sign on, like you posted. Ifter that I created user in DB Table Abp.User, when I start application, I´m I´m automaticly logged, so I click to log off button in rigth top menu and ˇim traing to log on by windows button and I got ERR_TOO_MANY_REDIRECTS ERROR. When i start APP again from VS by ctrl+f5, I got this ERROR too. Also I notice that Sometines it log me / semotines i got this error.

Second variant I turn off autoSIgn by removing path from Sartup to older version. And  after that I click to windows login button after taht I got error : The provided anti-forgery token was meant for user "HH\Martin", but the current user is "". ALso I noticed that somatines I´m logged.
Yes I have enabled anonymus auth.

I use VS2015 comunity edition and WINDOWS 10. I can send you my project again with setting of autosign.  

Thanks!

**Comment by MohammadYounes** [comment]
Using same setup as yours, here is the project I tested with (http://1drv.ms/1X3Hp6d)
> I uploaded only the web project excluding `Abp`, `App_Data`, `bin`,`obj`,`fonts`,`Logs` and `scripts`. Folders

**Comment by Klainer** [comment]
Ok, I tested your code on another computer with WIN7, but the same problem. After first startUp it show me Registration form, I register by windows pass/name. And after reopen page is redirection LOOP.
I´m not sure what or how it work to you so I prepred sample VIDEO of my problem:
https://mega.nz/#!uN8QSZiR!G30AjQ5lKY6N3j1LQHTx7V6S7VlIhO5xj67C3aoOflU
Also i prepared sample demo wit your changes:
https://mega.nz/#!DUMgAD7A!tCX0MeHbYA88WGfj4clgcBE97HixrtaqPaH9N51d8f4

**Comment by MohammadYounes** [comment]
@Klainer can you join me here https://gitter.im/MohammadYounes/OWIN-MixedAuth ?

**Comment by Klainer** [comment]
Hello, I have last question, if it is possible. In my local IIS express server everythink works OK thnaks to you. But application will be host on IIS SERVER, and will be use as intranet page for company. So only employes with their company notebooks will be automaticly logged when start this application. I deployed app on company IIS I have again this redirection loop problem. So it is necessarily to setup internet setting on IIS Server again or on all PC´S i company ?
Thanks
