### ISSUE TITLE
SID can change

### ISSUE THREAD

**Issue by Saquibadil** [MohammadYounes/OWIN-MixedAuth#31]
Hello,

Since in the UserLogin table we are recording the SID of the user, I did a search to see if the SID can change in the active directory for a user. According to this article, it can

https://blogs.msdn.microsoft.com/oldnewthing/20141128-00/?p=43513/

Do you have anything in place that checks the history of SID?

Thank you!
Saquib

**Comment by MohammadYounes** [comment]
Currently no,  I'll into it.

**Comment by MohammadYounes** [comment]
As far is OWIN-MixedAuth is concerned, the user is authenticated. Now, in case SID gets changed, it's up to the application to handle it.

You'll need to get the SID History and add to the custom claims [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/App_Start/Startup.Auth.cs#L82), Then deal with it in the account controller [`ExternalLoginCallback`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L325-L351)

Thanks!
