### ISSUE TITLE
SSO with Mixed Auth.

### ISSUE THREAD

**Issue by ahmadasfour** [MohammadYounes/OWIN-MixedAuth#32]
Dear Mohammad,

Kindly I want to ask the following questions:

1. If it is possible to use the mixed auth. along with SSO when login as windows and how?
2. I am using mixed auth on MVC, and I need to always log in as windows without the need to click the button, and this is applicable to open any controller/action and the system to get the windows identity, the same behavior when using Windows authentication

Please advise.

Thanks.

**Comment by MohammadYounes** [comment]
Hello Ahmad,

Yes, if you SSO server support any OWIN authentication provider, you should be able to use OWIN-MixedAuth in a similar manner.

As for the 2nd point, see this [comment](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443)

Thanks!

**Comment by ahmadasfour** [comment]
Thanks a lot for the reply Mohammad, for the SSO, would you please advise for the steps needed to plugin the mix auth. to SSO if any. Thanks.

**Comment by MohammadYounes** [comment]
There is no specific steps, it depends on your SSO implementation and whether it supports OWIN providers or not!

**Comment by ahmadasfour** [comment]
Thanks a lot :)

**Comment by ahmadasfour** [comment]
Another question please, is the mixed auth. supports the claims identity and how can use it?

**Comment by MohammadYounes** [comment]
Yes it does, What do you mean by how to use it! Can you be more specific ?

**Comment by ahmadasfour** [comment]
I have an MVC controller, calling WebApi controller ( login action ), and I want to use mixed auth. would you please advise how I can login to WebApi when the user login as windows (i.e. how to send windows credentials to WepApi login action). Thanks.

**Comment by MohammadYounes** [comment]
You need to hit the authorize end point to get an access token, then use it along with your Api calls. See the sample project named [SPA](https://github.com/MohammadYounes/OWIN-MixedAuth/tree/master/src/SPA) (The access token is retrieved [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L40-L53) and the Authorize end point is defined [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26)).

**Comment by ahmadasfour** [comment]
You mean I need to hit an Api controller to generate a token, if yes, based on what I want to generate it, actually I am using AspNetIdentity on the business logic layer, the BL is called by Api, and we are going to support forms and windows login, so, the login is done through Api, not MVC, our architecture was  to be able to remove the UI layer without effecting anything, so, there is no any dependency on the MVC.

Would you please advise. Thanks.

**Comment by MohammadYounes** [comment]
In both case you need to generate an access token, For forms authentication you need to use `Password Login Flow` on the [token endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L25) and for windows authentication you need to use `External Login Flow`  on the [authorization endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26). 

See http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api for more details

**Comment by ahmadasfour** [comment]
Thanks a lot Mohammad. appreciated. I will check and come back to you.

**Comment by ahmadasfour** [comment]
Dear Mohammad,

I have a case here, that is, I need when run a new IE session, and then click on windows button to display the windows login dialog not to login as the user previously logged in (saved by the cookie).
would you please advise.

Thanks.

**Comment by MohammadYounes** [comment]
See #4

**Comment by MohammadYounes** [comment]
Also [this comment](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/15#issuecomment-93966215) :)
