### ISSUE TITLE
Missing View?

### ISSUE THREAD

**Issue by WilliamDoman** [MohammadYounes/OWIN-MixedAuth#33]
Sorry, I'm not sure where the windows login button comes from in the MVC project. What am I not understanding?  Is there a missing view?  

Thanks!

**Comment by TrabacchinLuigi** [comment]
you have to configure the project then in the default login window (the one from the mvc template) you'll have a login button for every authentication provider

**Comment by WilliamDoman** [comment]
Thanks. 

I was a little confused because the button for Windows is off to the side in the picture.

**Comment by MohammadYounes** [comment]
All authentication providers will appear to the side, the list is generated by [this view](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Views/Account/_ExternalLoginsListPartial.cshtml)
