### ISSUE TITLE
Login with Windows and store claims in Cookie, no database

### ISSUE THREAD

**Issue by pcbHikeME** [MohammadYounes/OWIN-MixedAuth#35]
Mohammad- this is great stuff you have here.  I've been trying to modify your approach to really not use asp.net identity database, just authenticate a windows user and put claims in a custom cookie. And in addition if the user is already logged into Windows, don't prompt for credentials.  I took your suggestions in #8 and got that working, so now I'm trying to exclude all the db parts.  My problem is similar to what is described in #24.  Return from GetExternalLoginInfoAsync is always null.  I think that if I could just get from IIS/ASP.Net the Windows user (name and domain) I'd be all set.

**Comment by MohammadYounes** [comment]
Although the samples are using a database, but the provider is db free! 

`GetExternalLoginInfoAsync` returns null if no external cookie is available! Can you share a sample ?

**Comment by pcbHikeME** [comment]
Here's my ConfigureAuth (sorry - not sure why inline code not working)
`public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app)
        {
            CookieSecureOption cookieSecure = CookieSecureOption.SameAsRequest;
            if (Configurator.SpectrumAuth.UseSsl)
            {
                cookieSecure = CookieSecureOption.Always;
            }

            var cookieOptions = new CookieAuthenticationOptions
            {
                AuthenticationType = Configurator.SpectrumAuth.CookieName,
                LoginPath = new PathString("/" + Configurator.SpectrumAuth.LoginController + "/" + "WindowsLogin"),
                CookieDomain = Configurator.SpectrumAuth.CookieDomain,
                ExpireTimeSpan = new TimeSpan(0, Configurator.SpectrumAuth.CookieTimeToLiveMinutes, 0),
                CookieName = Configurator.SpectrumAuth.CookieName,
                CookieHttpOnly = true,
                CookieSecure = cookieSecure,
                SlidingExpiration = true
            };

            app.UseCookieAuthentication(cookieOptions);

            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseStageMarker(PipelineStage.Authenticate);

            //Enable Mixed Authentication
            //As we are using LogonUserIdentity, its required to run in PipelineStage.PostAuthenticate
            //Register this after any middleware that uses stage marker PipelineStage.Authenticate
            //See http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline      
            // Enable mixed auth
            app.UseMixedAuth(new MixedAuthOptions()
            {
                Provider = new MixedAuthProvider()
                {
                    OnImportClaims = identity =>
                    {
                        PrintCurrentIntegratedPipelineStage("impclaims");
                        List<Claim> claims = new List<Claim>();

                        using (var principalContext = new PrincipalContext(ContextType.Domain | ContextType.Machine))
                        {
                            using (UserPrincipal userPrincipal = UserPrincipal.FindByIdentity(principalContext, identity.Name))
                            {
                                if (userPrincipal != null)
                                {
                                    claims.Add(new Claim(ClaimTypes.Email, userPrincipal.EmailAddress ?? string.Empty));
                                    claims.Add(new Claim(ClaimTypes.Surname, userPrincipal.Surname ?? string.Empty));
                                    claims.Add(new Claim(ClaimTypes.GivenName, userPrincipal.GivenName ?? string.Empty));
                                }
                            }
                        }
                        return claims;
                    } 
                }

            }, cookieOptions);

            app.UseStageMarker(PipelineStage.PostAuthenticate);
        }
		
        private void PrintCurrentIntegratedPipelineStage(string msg)
        {
            var currentIntegratedpipelineStage = HttpContext.Current.CurrentNotification;
			Debug.WriteLine("Current IIS event: {0} Msg: {1}", currentIntegratedpipelineStage,msg);
        }
    }`
Windows login action:
`        [HttpGet]
        [AllowAnonymous]
        public ActionResult WindowsLogin(string returnUrl)
        {
            //Configurator.SpectrumAuth.HomeAction, Configurator.SpectrumAuth.HomeController
            return new ChallengeResult("Windows", Url.Action("ExternalLoginCallback", "Account", new { ReturnUrl = returnUrl }));
        }`
and heres the ExternalLoginCallback action
'        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
			
            var authMan = AuthenticationManager;

			// I have tried AuthenticationManager.User, but it is empty WindowsIndentity
			
			// always returns null
            var loginInfo = await authMan.GetExternalLoginInfoAsync();
			
			// 2 types - Windows and my custom cookie
            var authTypes = authMan.GetAuthenticationTypes();
            
			// i'm just trying things to find out what's going on
            foreach (var at in authTypes)
            {
                Debug.WriteLine("{0} {1}", at.AuthenticationType, at.Caption);
				// returns null
                var authRes = await authMan.AuthenticateAsync(at.AuthenticationType);
				// returns null
                var extID = authMan.GetExternalIdentity(at.AuthenticationType);
            }

			// here's where I force feed an AD user to my Cookie Authentication - this works, but how to not hard code it ?
            bool authed = Authorizer.CookieSignInByTrustedApplication(HttpContext, "myADusername", "mydomain");

            if (authed)
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(Configurator.SpectrumAuth.LoginAction, Configurator.SpectrumAuth.LoginController);
            }
        }'

**Comment by pcbHikeME** [comment]
Mohammad-
I found the problem.  This line `app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);` in the Startup.Auth.cs needed to be:
`app.SetDefaultSignInAsAuthenticationType(cookieOptions.AuthenticationType);` to use my custom cookie!

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
