### ISSUE TITLE
401 with Ajax and Css Calls

### ISSUE THREAD

**Issue by meister-d** [MohammadYounes/OWIN-MixedAuth#36]
Hi Mohammad, like engenb on the MVC5-MixedAuth I experience Issues with 401 errors while loading javascript and css files. In our Lab this issue does not bother, but on client side for every script the user is promted to login with username and password after logging in with Mixed auth. After something like 20 login forms he finally sees the correct website and can proceed. (On Client Side the Application is configured with an reverse Proxy setup for outside users)

To get this Working we tried to set the IIS_IUSR Account permission  to the Directory where the App is stored  (it is outside of the wwwroot) and we configured some paths to be excluded from auth eg:

```
<!-- Enable Mixed Auth -->
  <location path="MixedAuth">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
      <httpErrors errorMode="Custom">
        <remove statusCode="401"/>
        <error statusCode="401" path="401.html" responseMode="File" />
      </httpErrors>
    </system.webServer>
  </location>
  <location path="Content">
      <system.web>
        <authorization>
          <allow users="*"/>
        </authorization>
      </system.web>
  </location>
  <location path="Scripts">
    <system.web>
      <authorization>
        <allow users="*"/>
      </authorization>
    </system.web>
  </location>
  <location path="fonts">
    <system.web>
      <authorization>
        <allow users="*"/>
      </authorization>
    </system.web>
  </location>
  <system.webServer>
    <modules>
      <remove name="FormsAuthentication" />
    </modules>
  <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
```

We also have tried to set the Order of NTLM and Negotiate on the Windows Authentication in IIS but also this also didn't helped.

To illustrate our Issue I'v attached a fiddler trace below.

![2016-01-26_212136](https://cloud.githubusercontent.com/assets/7633269/12594108/a85580c0-c474-11e5-94b2-514e2e9ad875.jpg)

Any Idea why this can happen?

Regards meisterd

**Comment by MohammadYounes** [comment]
Hi,

The Paths you listed are excluded from authorization (not authentication).

What's the Authentication mode of your app ? Also in your IIS, is Anonymous authentication enabled ?

**Comment by ssteiner** [comment]
In IIS, we have anonynmous enabled, and windows auth enabled (with negotiate first, ntlm second).
here's the relevant rest of the web.config


  <location path="MixedAuth">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
      <httpErrors errorMode="Custom">
        <remove statusCode="401"/>
        <error statusCode="401" path="401.html" responseMode="File" />
      </httpErrors>
    </system.webServer>
  </location>
  <system.webServer>
    <modules>
      <remove name="FormsAuthentication" />
    </modules>
  <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers></system.webServer>

**Comment by MohammadYounes** [comment]
The relevant part would be `<system.web>` section, similar to [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Web.config#L21)!

**Comment by ssteiner** [comment]
Hmm.. that part somehow didn't make the copy/paste. Here it is

      <system.web>
        <authentication mode="None" />
        <compilation debug="true" targetFramework="4.5" />
        <httpRuntime targetFramework="4.5" />
        <globalization enableClientBasedCulture="true" uiCulture="auto:en-US" culture="auto:en-US" />
      </system.web>

**Comment by MohammadYounes** [comment]
Can you join me here https://gitter.im/MohammadYounes/OWIN-MixedAuth ?

**Comment by MohammadYounes** [comment]
Try to exclude them explicitly in your virtual host config:

```
<LocationMatch "/(Scripts|Content)">
	   RequestHeader unset Authorization
</LocationMatch>
```
