### ISSUE TITLE
using MVC : cannot login using windows button click

### ISSUE THREAD

**Issue by kamranbashir** [MohammadYounes/OWIN-MixedAuth#37]
1. Start up project MVC in OWIN-MixedAuth
2. windows login button clicked
3. showing HTTP Error 500.19 - Internal Server Error
4 .when i chekced in ExecuteResult, userid is coming null.same issue in MVC5-MixedAuth
thanks,

```C#
public override void ExecuteResult(ControllerContext context)
{
    var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
    if (UserId != null)
    {
       properties.Dictionary[XsrfKey] = UserId;
    }
    context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
 }
```

**Comment by MohammadYounes** [comment]
Most likely you got the error 500.19 because you didn't unlock the windows authentication section as described in the [README](https://github.com/MohammadYounes/OWIN-MixedAuth#running-the-samples)

Check the steps again and confirm!

**Comment by kamranbashir** [comment]
1.Set Authentication - Windows to Read/Write -done
2. <section name="windowsAuthentication" overrideModeDefault="Allow" /> - done

i assume reset are pre configured in ur example.

but still
HTTP Error 500.19 - Internal Server Error

only ur MVC5-MixedAuth works stratight away!
brother can u pls put only mvc working code.
thanks,

**Comment by MohammadYounes** [comment]
Can you provide the details for the 500.19 error ?

**Comment by kamranbashir** [comment]
Detailed Error Information:
Module	   WindowsAuthenticationModule
Notification	   AuthenticateRequest
Handler	   ExtensionlessUrl-Integrated-4.0
Error Code	   0x80070021
Config Error	   This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".
Config File	   \\?\C:\Users\kamranb\Downloads\OWIN-MixedAuth-master\OWIN-MixedAuth-master\src\MVC\web.config
Requested URL	   http://localhost:28128/MixedAuth?state=srVLoNfN9ztZKaR9-7mZcEZnv_L-un5DqVK6piUlg6SkRaEms7Bs5algNoRbS-8XG4Wa3xJbqU2WzlWhpsXybl6l7URekhfuAH2FY0_ivxOXQ3NcYfrCOrhxLgMkE4iLxr3VekH6jfd0yDIFlST1dw
Physical Path	   C:\Users\kamranb\Downloads\OWIN-MixedAuth-master\OWIN-MixedAuth-master\src\MVC\MixedAuth
Logon Method	   Not yet determined
Logon User	   Not yet determined
Request Tracing Directory	   C:\Users\kamranb\Documents\IISExpress\TraceLogFiles\MVC

Config Source:
   29:         <authentication>
   30:           <windowsAuthentication enabled="true" />
   31:         </authentication>

**Comment by MohammadYounes** [comment]
Yup the section is still locked, are you using VS2015 with IIS Express ?

**Comment by MohammadYounes** [comment]
You need to follow IIS Express config steps as described [here](https://github.com/MohammadYounes/OWIN-MixedAuth#iis-express)

**Comment by MohammadYounes** [comment]
Feel free to reopen if following the steps  didn't resolve the issue. Thanks!

**Comment by kamranbashir** [comment]
gave up :(

thanks

**Comment by MohammadYounes** [comment]
Why ? Join me here https://gitter.im/MohammadYounes/OWIN-MixedAuth

**Comment by kamranbashir** [comment]
finding it too hard.
do u live in pakistan

**Comment by MohammadYounes** [comment]
No, Why don't you join the chat? I'm trying to help you!!

**Comment by kamranbashir** [comment]
if u r in uk we can do team viewer.

**Comment by MohammadYounes** [comment]
send me your ID/PWD

**Comment by kamranbashir** [comment]
not now, not allowed in office
in evening

**Comment by kamranbashir** [comment]
is that ok?

**Comment by MohammadYounes** [comment]
Ok
