### ISSUE TITLE
AD: users and groups

### ISSUE THREAD

**Issue by Leon-O** [MohammadYounes/OWIN-MixedAuth#38]
Can you bring an example of the settings we must set to get the users and groups from AD? I having problems with this.

**Comment by MohammadYounes** [comment]
Not sure I understand your request! Would you please clarify ?

Also check #9

**Comment by Leon-O** [comment]
Thanks for the reference. I would like to know if is possible to implement Role based authorization, using the AD groups as roles, that's why I want to get all the groups from AD.

[Authorize(Roles="Administrators")]

**Comment by MohammadYounes** [comment]
Yes, as long as you convert them to role claims:
```c#
  foreach (var group in userPrincipal.GetGroups())
      identity.AddClaim(new Claim(ClaimTypes.Role, group.Name));
```

Also see this [discussion](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/3).

**Comment by Leon-O** [comment]
Perfect, thanks.

**Comment by arc95** [comment]
@MohammadYounes! Thanks. Where do call that `foreach`?
