### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MartyBJones** [MohammadYounes/OWIN-MixedAuth#39]
I have incorporated your code and everything is working great in the test environment.  I can authenticate local users via AD and external users via Forms authentication.  The problem comes into play when I deploy to production environment.  The production web server is within a DMZ and does not have direct access to Active Directory.   Is there a way I can still gather the user's windows information and possibly pass the information to an WCF service which would have access to Active Directory in order to pull the user's information?

**Comment by MohammadYounes** [comment]
The code relies on IIS integrated authentication to get the user identity, For IWA to work, IIS must be a member of Active Direcroty. If you are trying to pull more info from active directory, You could do that while [importing custom claims] (https://github.com/MohammadYounes/OWIN-MixedAuth#importing-custom-claims).

**Comment by MartyBJones** [comment]
I guess this will not work for me.  The problem is that IIS is running as a local user account on the web server (inside of DMZ).  It does not have access to the corporate AD.  I was hoping I could shift the concern to a WCF service but it sounds like with the IIS server having access to the AD then this will not work.

**Comment by MohammadYounes** [comment]
Yup, I guess this is why it's called integrated :)
