### ISSUE TITLE
500 on MixedAuth?state=

### ISSUE THREAD

**Issue by pcbHikeME** [MohammadYounes/OWIN-MixedAuth#40]
Mohammad-  Very much appreciate this work.  I am using the integrated auth variation and have it working on one IIS server but cannot get it on the other.  I keep getting a 500 Error when the code tries to invoke the URL below.  I have doubled checked all of the settings.  Nothing seems out of place.  Any ideas?
http://mysite/MixedAuth?state=KpFpRo_MKUxKgwFTkyaLv1ZVCjIn8Ox6e34ksTl7w9DX-7cSKfjKe8bC3ZDp-FJfcVj9MN6Y_9NLFsQS6SmUPbnwjnjHu8gWMmdiafJL1Uo48mLM-T8skYAx1xOsrH-NJPE7aZmvjv3zoyaUKs6_Z4ASKnGhUdTYstPTpgF_KJTgiKzmWajWfNmw7PFJQ-b_

**Comment by MohammadYounes** [comment]
It's hard to tell, If possible try using the source code and set a break point [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthHandler.cs#L93).

**Comment by pcbHikeME** [comment]
ok.  will try.  this is on a server so I will need to add some instrumentation to the source. (I cannot debug on server).  Are you saying this fragment should be true ?
Options.CallbackPath == Request.Path

**Comment by pcbHikeME** [comment]
My tracing/logging shows that callback path is /MixedAuth  More thoughts?

**Comment by pcbHikeME** [comment]
since it is returning 500 on http://mysite/MixedAuth?state= does that mean it's a server or config problem?

**Comment by MohammadYounes** [comment]
May be, 500 is a very generic error. Any stack trace!

**Comment by MohammadYounes** [comment]
The method will only execute when the paths are equal, I'm interested in what happens afterwards

**Comment by MohammadYounes** [comment]
Moreover, Are you using a MixedAuth provider?

**Comment by pcbHikeME** [comment]
I see that [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthHandler.cs#L206) is where that redirect is generated.  So I logged the URI and the redirectContext.Response.ReasonPhrase.  ReasonPhrase is Found.  URI looks like the one that is generating the 500

**Comment by pcbHikeME** [comment]
Yes I am using your MixedAuth but am using the Autologin modification you suggested [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443)

**Comment by pcbHikeME** [comment]
I do see this in the web.config at the servers root.  Could that be a problem?
`    <system.web>
        <identity impersonate="false" />
    </system.web>`

**Comment by MohammadYounes** [comment]
The error is generated after the redirect. as for the impersonation, what you listed is the default, so it should not be a problem

**Comment by MohammadYounes** [comment]
Can you confirm the windows authentication section is unlocked on the server ?

**Comment by pcbHikeME** [comment]
showing you the snagit of the IIS feature deleg.  I restrted IIS After I set this (several hrs back)
![2016-04-01_18-50-11](https://cloud.githubusercontent.com/assets/10076004/14222119/d89df79a-f83a-11e5-8fbd-bb21a3d2400d.png)

**Comment by MohammadYounes** [comment]
Any stack trace you can share ?

**Comment by pcbHikeME** [comment]
I will have to leave this for now as it's quite late my time.  I will provide that in a couple of days.  Very much appreciate your help.  Thanks, Mohammad

**Comment by pcbHikeME** [comment]
I think I just found the problem!  Options.CallbackPath != Request.Path  It looks like Request.Path is / and as stated above Options.CallbackPath is /MixedAuth   Where did I go wrong ?

**Comment by MohammadYounes** [comment]
That's normal, as this method is invoked on each request. It's contents will only be executed if the paths are equal

**Comment by pcbHikeME** [comment]
Yes, I see that.  But on this server, the paths are never equal (Request.Path never equals /MixedAuth), whereas on the server where it is functioning the equality does happen.  thoughts?

**Comment by pcbHikeME** [comment]
checking handlers on non-working web server.  Do you think that could be a problem?

**Comment by pcbHikeME** [comment]
there is no stack trace in .net because there does not appear to be any failure in the code.  I look at the  IIS log and I see that the sc-win32status code (after the 500.19) is 33, which is ERROR_LOCK_VIOLATION
33 (0x21)
The process cannot access the file because another process has locked a portion of the file

I am trying to get IIS tracing turned on but have not had any luck with that

**Comment by MohammadYounes** [comment]
Have you tried [Troubleshooting HTTP 500.19 Errors in IIS 7](https://blogs.msdn.microsoft.com/webtopics/2010/03/08/troubleshooting-http-500-19-errors-in-iis-7/)?

**Comment by pcbHikeME** [comment]
So i just looked at that and unfortunately I have less to go on than that.  See Screen shot below.  I believe that the request is not being handled by your MixedAuth code - that seems like the issue.  Which leads me to agree it's a IIS config error and probably handler problem - but I have tried shifting around the extension-less handlers without luck.  Cannot get tracing to log anything.  Maybe I just need to config this site on this server to have exactly the same handlers in same order as the server where it's working?
![2016-04-04_16-21-13](https://cloud.githubusercontent.com/assets/10076004/14262111/d29faeb2-fa81-11e5-8603-e8a1a2f738c3.png)

**Comment by MohammadYounes** [comment]
Can't you set [customErrors](https://msdn.microsoft.com/en-us/library/h0hfz6fc%28v=vs.85%29.aspx) mode so the detailed ASP.NET errors are shown  ?

**Comment by pcbHikeME** [comment]
SO if I do that whether it's mode="On" or "Off" I get the same error display as above.  So I think that shows us that the request is not even getting to ASP.Net, wouldn't you think ?

**Comment by MohammadYounes** [comment]
Not sure, may be try with `<compilation debug="true"/>`, Can you join the [chat](https://gitter.im/MohammadYounes/OWIN-MixedAuth) ?

**Comment by pcbHikeME** [comment]
Hmm, I wonder if this could be it ?   [IIS 7.5 handlers to handle requests whose URLs do not end with a period](https://support.microsoft.com/en-us/kb/980368)

**Comment by MohammadYounes** [comment]
Give it a try!

**Comment by pcbHikeME** [comment]
I give up.  Can't spend any more time on this. Clearly a config issue on that IIS Server.  Thanks for your time, Mohammad

**Comment by MohammadYounes** [comment]
@pcbHikeME  You are most welcome, in case you find the reason behind this, please update me.

Thanks!
