### ISSUE TITLE
Mixed Auth repeatedly request Windows creds

### ISSUE THREAD

**Issue by pcbHikeME** [MohammadYounes/OWIN-MixedAuth#41]
Hi Mohammad-
I'm trying my approach based on [this comment](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443) on a new IIS (8.5) server and I get the following behavior.  Repeatedly asks for credentials and never works.  I have set Windows Auth to read/write.  What would cause this ?
![2016-04-05_10-39-47](https://cloud.githubusercontent.com/assets/10076004/14285901/2dfb0d1c-fb1b-11e5-936e-765a923162ce.png)

**Comment by MohammadYounes** [comment]
I can't tell, re-check your configuration! Also try providing full username (user@domain).

**Comment by pcbHikeME** [comment]
Thanks, I'm giving up on this as well.  Seems to be a similar to [my prior issue](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/40).  I've done a lot of configuration work and can't find what's going on.

**Comment by MohammadYounes** [comment]
Sorry I couldn't be of help, but without details my hand are tight. In case you find what's wrong with your setup, please update me.

Thanks.
