### ISSUE TITLE
Getting the wrong user

### ISSUE THREAD

**Issue by ObrellusRex** [MohammadYounes/OWIN-MixedAuth#42]
Hi,

I have an issue where everything works as it should in development and testing environments but our production system unfortunately gets user identity and groups for the AppPool user instead of the user accessing it.

All configurations related to authentication is matching. Are you able to point me in the right direction for further troubleshooting?

My other option is to rewrite/split the site and only use windows authentication.

**Comment by MohammadYounes** [comment]
Hi,

Does this happen to all clients trying to connect to the production server? Also does the same thing happen with the included samples?

Thanks!

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
