### ISSUE TITLE
Unable to link to an existing local account

### ISSUE THREAD

**Issue by Adam-78** [MohammadYounes/OWIN-MixedAuth#43]
If a user already has a local account and they click the login with windows button, they are redirected to the 'Associate your windows account' page where they are presented with an input field to enter an email address. 

When you enter an email address that is already registered with your local account, it throws error message:

  Name joe.blogs@yahoo.com is already taken.
  Email 'joe.blogd@yahoo.com' is already taken.

It is therefore forcing the user to create a new account? The only way I can overcome this at present is by login in via the local account and using the manage account page to link with an external provider.

Is there any way to link the account directly from the 'Associate your windows account' page?

I have an intranet application and would like existing user with local accounts to simply login using the windows button and entering their registered email address.

**Comment by MohammadYounes** [comment]
This is the MVC project template default behavior. If sign in using Windows account while not being logged in, The application will see you as a new user ([ExternalLoginConfirmation](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Views/Account/ExternalLoginConfirmation.cshtml)). It can't verify your ownership to both accounts as you are logged in with only one of them.

The only way you mentioned is the correct one, as the application would be able to verify that both accounts belong to the same user and link them.

However, you could implement your own logic to allow logging in with the local account along with the [external login confirmation](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L352-L389).
