### ISSUE TITLE
Claim (roles) Problem

### ISSUE THREAD

**Issue by stratdaz** [MohammadYounes/OWIN-MixedAuth#45]
I'm trying to add a role (AdminRole) and secure `Get()` in the `MeController` with ...

``` c#
[Authorize(Roles = `"AdminRole")]
```

I'm adding the role here ...

``` c#
app.UseMixedAuth(new MixedAuthOptions()
{
    Provider = new MixedAuthProvider()
    {
        OnImportClaims = identity =>
        {
            List<Claim> claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Role, "AdminRole"));
            return claims;
        }
    }
}, cookieOptions);
```

I'm using the windows login option and it seems that the role is being added to my domain identity user with the name _MYDOMAIN\MyUserName_ and `AuthenticationType` "". 

But in the `AccountController` ...

``` c#
public ActionResult Authorize()
```

The `ClaimsIdentity` is not the same identity that the role was added to and, although authenticated, does not contain the role and has the name with my email address with `AuthenticationType "ExternalCookie"`.

I am using IIS and have the SPA site set to Anonymous only. 

Can you spot where I'm going wrong?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

This is the default behavior, Imported claims will be added to the claims list of the external identity (windows identity, Not the local identity).

Upon user registration or account linking you need to read those claims and save them along the local user identity claims.  

Thanks!

**Comment by stratdaz** [comment]
Thanks Mohammad,

Wish I had as good an understanding of authentication as you but I don't. I've been looking for a solution to my problem for a while now and stumbled across your project thinking it would be the answer.

My situation ...

I have a web app running on an intranet. All users are members of the domain, we use windows authentication and everything works great.

Now we have users external to our organisation who also need to use the app but they are not members of our domain. I can authenticate them in other ways so that's not the problem. 

The ideal setup is if the application could work out the identity of the user coming in. If a windows user then authenticate accordingly and issue a token and if an external user then authenticate against an internal database before issuing a token. The application runs within the framework of another so I have secure ways to authenticate external users without the need to ask for username and password.

As an alternative I can set up the web app on two separate sites and have one configured for windows authentication and one for forms.

Reading through the documentation and issues and it seems OWIN-MixedAuth is dependent on every user (internal or external) having a windows identity (domain account).

Do I have that right and this will not work as I expect and every user does need to be a domain member?

Thanks for your time.

**Comment by MohammadYounes** [comment]
@stratdaz In essence a mixed mode is a cookies authentication with a windows authentication entry point, once the user gets passed it, the normal cookies authentication flow takes place.

Similar to other authentication providers, such as Google, Twitter ... etc. OWIN-MixedAuth is a simple windows authentication provider that authenticates using IIS Integrated Windows Authentication (IWA) which provides you with the Windows Identity as an external one. 

Using asp.net identity, every user in your app must have a local identity (username/password), linked with one or more external identities (Windows, Google, Twitter or even Custom Identity).

The local identity, is what uniquely identifies the user through out your app. It does not need to have the password set, with empty password users will be able to log in using their external identities only.

> The ideal setup is if the application could work out the identity of the user coming in. If a windows user then authenticate accordingly and issue a token and if an external user then authenticate against an internal database before issuing a token. The application runs within the framework of another so I have secure ways to authenticate external users without the need to ask for username and password.

I see this as having two providers, OWIN-MixedAuth for Windows Identities and a Custom-Auth for Custom Identities authenticated against an internal database or a different app. At the same time, have empty password for all local identities and remove the normal forms authentication UI from your app.

Hope this helps!
Thanks.

**Comment by stratdaz** [comment]
Thanks for the extra detail. 

I now have my own ApplicationDbContext, ApplicationUser, ApplicationUserManager and ApplicationSignInManager. 

Have configured OAuth with a login path of ... 
LoginPath = new PathString("/Account/WindowsLogin") ... to automatically sign in AD users.

Also AccountController has an "AutoLogin" method to automatically sign in external users and is referenced in a 401.html page as per post [#8]("https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-76956157")

Not sure if this is the right approach but seems to work although needs more testing.

Thanks for your time Mohammad.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
