### ISSUE TITLE
Always asking for credentials

### ISSUE THREAD

**Issue by SoaresMG** [MohammadYounes/OWIN-MixedAuth#46]
Hi again,

I'm getting a weird problem.
So, one of my clients have two systems:
- Production (Cluster w/ Load Balancer)
- Development (1 VM)

In the development system we had some problems but it was resolved through feature activation (Windows Identity Foundation, Security -> Windows Authentication, and more).

However, on Production we have a weird problem.
When opening the website it asks for credentials (as it should be) but introducing them and cliking "OK", it shows the same NTLM/Negotiate window to enter credentials and so on. This window doesn't close.

The strange thing is that it works on Firefox but not on IE/Chrome. Browsers were tested on 2 different machines.

I already checked for all roles and features and it was identical to development server.
I even tought it could be the user running the application pool, but it isn't (I've changed the user to an AD user).

Are you aware of any situation like this?
I'm 95% sure it's Load Balancers's fault. 
If you have already faced this problem or if you have any test that i could perform, please let me know.

Regards,
Leandro Soares

**Comment by MohammadYounes** [comment]
Hi, Have you synchronized the `machinekey` between all servers ?

**Comment by LESARQ** [comment]
Are you talking about Load balancer? Between the cluster servers?
Our customer has the cluster working with more applications and we don't have access to those type of configurations.

**Comment by SoaresMG** [comment]
I see, probably no.
But, isn't it generated for each application if you set it at IIS Server level?

**Comment by MohammadYounes** [comment]
May be this would help https://blogs.technet.microsoft.com/askds/2011/08/09/kerberos-and-load-balancing/

**Comment by SoaresMG** [comment]
I'll call the customer today or tomorrow and will test this with him.
I'll give you feedback asap.

Thank you

**Comment by SoaresMG** [comment]
Ok, we synchronized the machine keys and it still doesn't work

**Comment by SoaresMG** [comment]
It's working now. There was some problem with _Negotiate_ so we just moved _NTLM_ above _Negotiate_ and it started working. 

Thank you again for your time. :smiley:

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
