### ISSUE TITLE
how to get the current login user details from home controller

### ISSUE THREAD

**Issue by nityadao** [MohammadYounes/OWIN-MixedAuth#47]
Hello Mohammad,

I have problem in getting current login user details from home controller in both the cases ( form + windows authentication).

thanks

**Comment by MohammadYounes** [comment]
Hello,

What kind of problem ? What's the value of `User.Identity` ?

Thanks!

**Comment by nityadao** [comment]
Hello,

User.Identity is present but when i am using UserManager.FindById(User.Identity.GetUserId()); then its show me Object reference not set to an instance of an object message. and User.Identity.GetUserId() is also present.

public ApplicationUserManager UserManager
        {
            get
            {
//error shows at this location
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

**Comment by MohammadYounes** [comment]
Too many objects involved in your call, which one is the `Null` one ?

**Comment by nityadao** [comment]
error at this line
return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

**Comment by MohammadYounes** [comment]
Can you join here https://gitter.im/MohammadYounes/OWIN-MixedAuth ?

**Comment by MohammadYounes** [comment]
Did you initialize the User Manager in your app start ?

``` c#
app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
```

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
