### ISSUE TITLE
500 - Internal server error after deploying to production?

### ISSUE THREAD

**Issue by Adam-78** [MohammadYounes/OWIN-MixedAuth#48]
Hi,

I've installed the OWIN-MixedAuth to an MVC application and it work fine on my local machine using IIS Express. 

However after deploying to production server I get 500 - Internal server error?

The site is deployed to a folder called `mysite` which is configured as an application as follows so bascially it inside its own app pool:

xyx.domain.com/mysite

My web config file is as follows:

 `

```
 <system.web>
    <customErrors mode="Off"/>
    <authentication mode="None" />
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5.2" />
</system.web>
<!-- Enable Mixed Auth -->
<location path="MixedAuth">
    <system.webServer>
        <security>
            <authentication>
                <windowsAuthentication enabled="true" />
            </authentication>
        </security>
    </system.webServer>
</location>
<system.webServer>
     <modules>
        <remove name="FormsAuthentication" />
    </modules>
    <handlers>
        <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
        <remove name="OPTIONSVerbHandler" />
        <remove name="TRACEVerbHandler" />
        <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers></system.webServer>`
```

Any ideas why this is happening. Have I missed something out?

**Comment by MohammadYounes** [comment]
Have you [unlocked](https://github.com/MohammadYounes/OWIN-MixedAuth#iis) Windows Authentication section ?

**Comment by Adam-78** [comment]
Hi,
Still awaiting a screenshot from our server team to determine exactly what delegation mode has been configured - I did ask them enable windows auth as follows:

Set Authentication - Forms to Read/Write
Set Authentication - Windows to Read/Write
Change the app pool from classic mode to integrated pipeline mode

Does anonymous authentication need to be disabled as well?

**Comment by MohammadYounes** [comment]
Hi, 

No, Also there is no need to unlock the Forms authentication section.

**Comment by Adam-78** [comment]
With anonymous authentication enabled, windows authentication doesn't work. To configure Windows auth on IIS you need to disable anonymous authentication. But once you do that how can a unauthenticated reach the signin page?

**Comment by MohammadYounes** [comment]
That's why we unlocked the section, so we can enable Windows authentication for a sub-path - the MixedAuth endpoint only.

``` xml
  <!-- Enable Mixed Auth -->
  <location path="MixedAuth">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
    </system.webServer>
  </location>
```

**Comment by Adam-78** [comment]
I've managed to get it working. 

This was the issue, my site is located at `xyz.domain.com/mysite` but in my webconfig I have the path as `<location path="MixedAuth">` 

It should have been `<location path="MySite/MixedAuth">`. So basically it was redirecting to `xyz.domain.com/MixedAuth` instead of `xyz.domain.com/mysite/MixedAuth`

Many thanks for your help.

**Comment by MohammadYounes** [comment]
Awesome, Thanks for the feedback!
