### ISSUE TITLE
Imported Claims not found

### ISSUE THREAD

**Issue by jckh1234** [MohammadYounes/OWIN-MixedAuth#49]
I run the sample program. In the Start.Auth.cs , it have add additional claims of EmailAddress, Surname and Givename at the OnImportClaims. 

However , when I set a break point at the controller method, I don't found these 3 additional claims.

It only have four claims, that are "nameidentifier", "name", "identiyprovider" and "AspNet.Identity.SecurityStamp"

**Comment by MohammadYounes** [comment]
Hi,

This is the default behavior, Imported claims will be added to the claims list of the external identity (windows identity, Not the local identity).

Upon user registration or account linking you need to read those claims and save them along the local user identity claims.

Thanks!

**Comment by TrabacchinLuigi** [comment]
in the default asp.net project template you can find in the `AccountController.cs`  a function called `ExternalLoginCallback(string returnUrl)` 
in there you have:
`var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();`
this variable holds the claims that have been imported.
 and you can find the user by doing: 
`var user = await UserManager.FindAsync(loginInfo.Login);`
I suggest to find the user once you have successfully logged in hence inside the switch statement, then do whatever you like, i do save some claims in the db using the usermanager.
