### ISSUE TITLE
GetUserId() returns null in ManageController 

### ISSUE THREAD

**Issue by bdongus** [MohammadYounes/OWIN-MixedAuth#50]
Hi there.
I have a strange issue. Locally with VS2015 on Win10 everything works fine.

Installing everything on a Windows 2008 R2 server, within an AD domain, logged in users have no user id.

Setting a break point User.Identity is a ClaimsIdentity locally. This works. On the W2008R2 server it is a WindowsIdentity returning null as user id. The NameIdentifier claim is missing.

And I have no idea why. Any help is appreciated.

MixedAuth responses this on the w2k8R2 server:

```
HTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: /de-de/account/externallogincallback/?ReturnUrl=%2Fde-de%2Fmanage%2Findex%2F
Server: Microsoft-IIS/7.5
Set-Cookie: .AspNet.ExternalCookie=...some stuff removed for brevity...; path=/; HttpOnly
Persistent-Auth: true
X-UA-Compatible: IE=edge,chrome=1
Date: Wed, 31 Aug 2016 11:08:24 GMT
Content-Length: 0
```

MixedAuth response look like this locally:

```
HTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: /de-de/account/externallogincallback/?ReturnUrl=%2Fde-de%2Fmanage%2Findex%2F
Server: Microsoft-IIS/10.0
Set-Cookie: .AspNet.ExternalCookie=...some stuff removed for brevity...; path=/; HttpOnly
X-SourceFiles: =?UTF-8?B?VzpcaWRlZTUuRGlzcGF0Y2hlclxpZGVlNURpc3BhdGNoZXJcaWRlZTUuRGlzcGF0Y2hlclxNaXhlZEF1dGg=?=
Persistent-Auth: true
X-UA-Compatible: IE=edge,chrome=1
Date: Wed, 31 Aug 2016 11:18:57 GMT
Content-Length: 0
```

**Comment by MohammadYounes** [comment]
Looks like a problem with you Sign In logic, `ManageController` requires authorization, as such the identity should be a ClaimsIdentity.  In MixedAuth the WindowsIdentity is only used to create the ExternalIdentity.

How did you configure the application authentication? Did you enable the IWA for the MixedAuth endpoint only (as described in the README) ? 

Did you try running the samples on the W2008R2 machine ? What results did you get ?  

Thanks!

**Comment by bdongus** [comment]
The IIS delegation config has an additional entry: Standard - Read-Only

My auth cnfiguration:

```
    public void ConfigureAuth(IAppBuilder app, Container container) {
        app.CreatePerOwinContext(() => container.GetInstance<ApplicationUserManager>());
        app.CreatePerOwinContext(() => container.GetInstance<ApplicationRoleManager>());
        app.CreatePerOwinContext(() => container.GetInstance<ApplicationSignInManager>());

        var cookieOptions = new CookieAuthenticationOptions {
            AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
            LoginPath = new PathString(ConfigurationManager.AppSettings["LoginPath"]),
            Provider = new CookieAuthenticationProvider {
                OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, IdentityUser, Guid>(
                TimeSpan.FromMinutes(30),
                async (manager, user) => await user.GenerateUserIdentityAsync(manager),
                (id) => new Guid(id.GetUserId())),
            }
        };
        app.UseCookieAuthentication(cookieOptions);

        app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
        app.UseTwoFactorSignInCookie(DefaultAuthenticationTypes.TwoFactorCookie, TimeSpan.FromMinutes(5));
       app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);

        app.UseMixedAuth(cookieOptions);
    }
```

web.config contains this in system.web:

> ```
> <authentication mode="Windows" />
> ```

and this:

```
<location path="MixedAuth">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
    </system.webServer>
</location>
```

I didn't try the samples yet. Working on it.

**Comment by bdongus** [comment]
Okay. I got it solved.

> Important! Enabling windows authentication for a sub path requires windowsAuthentication section to be unlocked at a parent level.

Mislead me to set

> <authentication mode="Windows" />

Setting the mode to "None" did the trick. Why this isn't an issue on my local machine? No clue, but it doesn't matter.

Thank you for your quick answer.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
