### ISSUE TITLE
I got some problems with DatabaseFrist

### ISSUE THREAD

**Issue by MyronJi** [MohammadYounes/OWIN-MixedAuth#51]
The sample works very well.
And I have a program that uses a database first, and now needs to be added to the authentication.
But when I change the connectionString 
Like this:

`<add name="DataFirstEntities" connectionString="metadata=res://*/Models.Model1.csdl|res://*/Models.Model1.ssdl|res://*/Models.Model1.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=192.168.1.155;initial catalog=DataFirst;persist security info=True;user id=sa;password=sasa;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />`

And i change "DefaultConnection" in IdentityModels.cs to "DataFirstEntities" 

Then i got this error:
`The entity type IdentityUserLogin is not part of the model for the current context.`

I have created the required tables in mine database.

Can you help me? @MohammadYounes 
Thanks very much！

**Comment by MohammadYounes** [comment]
Error seems related to your EF not recognizing the model `IdentityUserLogin`, see the following SO posts:
-  http://stackoverflow.com/questions/23893710/the-entity-type-applicationuser-is-not-part-of-the-model-for-the-current-context.
-  http://stackoverflow.com/questions/20688922/the-entity-type-type-is-not-part-of-the-model-for-the-current-context

Thanks!

**Comment by MyronJi** [comment]
Thank you very much for your reply！

I fix the error by creating a standard connection string that pointed to the database where the ASP.NET Identity tables are.
[http://stackoverflow.com/questions/23893710/the-entity-type-applicationuser-is-not-part-of-the-model-for-the-current-context](url)

**Comment by MohammadYounes** [comment]
Great, Thanks for the feedback!
