### ISSUE TITLE
Automatic Login if AD Account exists?

### ISSUE THREAD

**Issue by SolarStorm50** [MohammadYounes/OWIN-MixedAuth#52]
Im new to using AD as an authentication provider.  I would be most grateful if you had any guidance as to how to implement this to automatically login if the user has an AD account?

IE what I am trying to do is:
1.  Attempt a login using windows authentication automatically.
2.  If they dont have a windows ID, show the login screen.

Thanks for sharing this solution

**Comment by MohammadYounes** [comment]
Follow the steps in  https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443. Let me know if you need further assistance!

**Comment by SolarStorm50** [comment]
Perfect!  If I can ever buy you a beer, I owe you a couple!  Thanks

**Comment by DanPFW** [comment]
Could you please describe how to do this with WebForms rather than MVC.  Thanks

**Comment by MohammadYounes** [comment]
@DanPFW Same steps, but instead of a WindowsLogin action, you need a WindowsLogin page

**1. Startup.Auth.cs**: Change `LoginPath` to point to Windows Login Page

``` C#
LoginPath = new PathString("/Account/WindowsLogin.aspx")
```

**2. WindowsLogin.aspx.cs**: On `PageLoad` request the windows challenge.

``` C#
protected void Page_Load(object sender, EventArgs e)
{
  string redirectUrl = ResolveUrl(String.Format(CultureInfo.InvariantCulture, "~/Account/RegisterExternalLogin?{0}={1}&returnUrl={2}", IdentityHelper.ProviderNameKey, "Windows", ReturnUrl));
  var properties = new AuthenticationProperties() { RedirectUri = redirectUrl };
  Context.GetOwinContext().Authentication.Challenge(properties, "Windows");
  Response.StatusCode = 401;
  Response.End();
}
```

**Comment by DanPFW** [comment]
This is great, I've updated your sample WebForms site, however, I'm having 2 issues.  First, I'm getting an error related to ReturnUrl in the PageLoad code, and I'm not able to get the code to automatically authenticate.  I've included the 401.html page and tried disabling the anonymous access, but the code will not run.  thanks

**Comment by MohammadYounes** [comment]
For the ReturnUrl, you'll need to read it from the query `Request.QueryString["ReturnUrl"]`. 

Have you followed all steps ?

> **1. Startup.Auth.cs**: Change `LoginPath` to point to Windows Login Action
> 
> ``` C#
> LoginPath = new PathString("/Account/WindowsLogin"),
> ```
> 
> **2. WindowsLogin.aspx.cs**: On `PageLoad` request the windows challenge.
> 
> ``` C#
> protected void Page_Load(object sender, EventArgs e)
> {
>   string redirectUrl = ResolveUrl(String.Format(CultureInfo.InvariantCulture, "~/Account/RegisterExternalLogin?{0}={1}&returnUrl={2}", IdentityHelper.ProviderNameKey, "Windows", Request.QueryString["ReturnUrl"]));
>   var properties = new AuthenticationProperties() { RedirectUri = redirectUrl };
>   Context.GetOwinContext().Authentication.Challenge(properties, "Windows");
>   Response.StatusCode = 401;
>   Response.End();
> }
> ```
> 
> **3. 401.html**: Add 401.html error page to your app root that will redirect to the normal login page:
> 
> ``` HTML
> <!DOCTYPE html>
> <html>
> <head>
>     <title></title>
>     
>     <meta http-equiv="refresh" content="0;URL='/Account/Login'" />
> </head>
> <body>
>     Invalid credentials, redirecting ...
> </body>
> </html>
> ```
> 
> **4. Web.config**:  Use 401.html to respond to 401 HTTP error (in case of login failure): 
> 
> ``` XML
> <system.webServer>
>     <httpErrors errorMode="Custom">
>       <remove statusCode="401"/>
>       <error statusCode="401" path="401.html" responseMode="File" />        
>     </httpErrors>
> </system.webServer>
> ```

**Comment by DanPFW** [comment]
yes, I've double checked my code, but when I start the app, i still see "Log in" at the top, rather than my AD user name.  Maybe I'm missing something simple.  thanks
1. Startup.Auth.cs:

```
           var cookieOptions = new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/WindowsLogin.aspx"),
                Provider = new CookieAuthenticationProvider
                {
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
              validateInterval: TimeSpan.FromMinutes(30),
              regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
                }
            };
```
1. WindowsLogin.aspx.cs:

```
        protected void Page_Load(object sender, EventArgs e)
        {
            string redirectUrl = ResolveUrl(String.Format(CultureInfo.InvariantCulture, "~/Account/RegisterExternalLogin?{0}={1}&returnUrl={2}", IdentityHelper.ProviderNameKey, "Windows", Request.QueryString["ReturnUrl"]));
            var properties = new AuthenticationProperties() { RedirectUri = redirectUrl };
            Context.GetOwinContext().Authentication.Challenge(properties, "Windows");
            Response.StatusCode = 401;
            Response.End();
        }
```
1. 401.html:

```
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <!-- redirect to normal login page -->
    <meta http-equiv="refresh" content="0;URL='/Account/Login.aspx'" />
</head>
<body>
    Invalid credentials, redirecting ...
</body>
</html>
```
1. Web.config:

```
    <system.webServer>
        <httpErrors errorMode="Custom">
            <remove statusCode="401" />
            <error statusCode="401" path="401.html" responseMode="File" />
        </httpErrors>
        <modules>
            <remove name="FormsAuthentication" />
        </modules>
    </system.webServer>
```

**Comment by MohammadYounes** [comment]
Yes, this is the normal behavior, you will be automatically signed in once you request a page that requires authentication. For example: navigate to `/Account/Manage`.

**Comment by DanPFW** [comment]
Looks like I got it working, thanks for all your help.
