### ISSUE TITLE
Error 500.19

### ISSUE THREAD

**Issue by MrBeezel** [MohammadYounes/OWIN-MixedAuth#53]
Hello,
I'm trying to use the SPA example but every time I try to authenticate through windows authentication I get the same error 500,19. I have configured IIS Express as you indicate but still the error persists. 
Any idea what the cause might be?

Thanks for your support.

**Comment by MrBeezel** [comment]
Ok, i just find the cause. I forgot to enable windows authentication in visual studio properties.
Anyway, thanks for all.

**Comment by MohammadYounes** [comment]
Thanks for the feedback.
