### ISSUE TITLE
I manually deleted the windows authenticated user from AspNetUsers table then I try to login but application always prompt to register email even after second time email registration

### ISSUE THREAD

**Issue by ajimr** [MohammadYounes/OWIN-MixedAuth#55]
Hi Mohammad, Thanks for the precise source code, when I try to evaluate the application in order to use one of my application I have found  following issue. Please let me know what will be the problem

Step 1:
After successful windows login application prompt for register email id and then there is entry in the  AspNetUsers table.
Step 2:
Then my subsequent windows login i could able to enter the application with out any issue.
Step 3: 
then I manually deleted the windows authenticated user from AspNetUsers table
Step 4:
Then when I try to login application again prompt for register email and I registered the email id.
Step 5: 
But then my subsequent windows login it always prompt for register email id rather than login.

**Comment by MohammadYounes** [comment]
Hi,

I tried the scenario you described, and I was able to login normally, I wasn't able to reproduce Step 5.

I conducted my test on the samples included in this repo.  Try to check any modifications you've made.

Thanks!

**Comment by ajimr** [comment]
Hi,

Thanks a lot for prompt response.

I am facing this problem only with windows Authentication.
I could use form authentication without any issue even after I delete the user from AspNetUsers table.

The following code return "Failure"
var result = await SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false);

If I point different database ( I have another non-deleted database) it works.

Only code Ichange I have done is  instead of ContextType.Domain I changed as ContextType.Machine, since earlier one produce LDAP server not found error.

 using (var principalContext = new PrincipalContext(ContextType.Machine))

Any clue? 

Thanks

**Comment by MohammadYounes** [comment]
I can't reproduce this, can you join [here](https://gitter.im/MohammadYounes/OWIN-MixedAuth) ?

**Comment by ajimr** [comment]
Thanks Mohammad for your timely response,  the issue is ,  I deleted the user data from AspNetUsers table but there is one more table AspNetUserLogins which has "deleted" user's data. once I deleted the data from second table, every thing works well. Thanks a lot Mohammad for helping me to identify the issue !:)
