### ISSUE TITLE
How do I limit the application authentication only for specific domain users in the windows login context.

### ISSUE THREAD

**Issue by ajimr** [MohammadYounes/OWIN-MixedAuth#56]
Hi Mohammad,

How do I restrict the application access to specific domain users, since now any domain users  can access the application as a windows users.

Advance thanks
Ajith

**Comment by MohammadYounes** [comment]
Hi Aji,

The easiest way would be to by add some logic inside the [ExternalLoginCallback](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L333) action to allow/deny users.

Thanks!

**Comment by MohammadYounes** [comment]
@ajimr  Scratch that configuration option, add your custom logic to the external login callback action.

**Comment by ajimr** [comment]
Ok Thanks.
