### ISSUE TITLE
500 internal Server Errror  ?state=2BD4u......

### ISSUE THREAD

**Issue by meister-d** [MohammadYounes/OWIN-MixedAuth#57]
Hi Mohammad,
like in the Issue #40 I experience the same errors. As you stated I set the Breakpoint and saw, that there could be a Problem when the webpage is not in the "root" Directory.

My Webpage starts with following Url: 

![websitesetup](https://cloud.githubusercontent.com/assets/7633269/22332228/11e8f460-e3d0-11e6-85b7-a0fcf1ac37f6.jpg)

If no modifications to the Callback Path are made I get this Error:

![withoutoptions modif](https://cloud.githubusercontent.com/assets/7633269/22332246/34dd7806-e3d0-11e6-9264-68cf8e4edddf.jpg)

I modified the Code this way:

![modification for mixedauth options](https://cloud.githubusercontent.com/assets/7633269/22332261/48731182-e3d0-11e6-884e-1eae91eac3ad.jpg)

Now it seems working fine:

![withoptions modif](https://cloud.githubusercontent.com/assets/7633269/22332270/57846608-e3d0-11e6-8702-58056f07be75.jpg)

I saw that I also can Modify StartupAuth.cs

```
app.UseMixedAuth(new MixedAuthOptions()
            {
                CallbackPath = new PathString("/AUDM/MixedAuth"),
                Provider = new MixedAuthProvider()
                {
                }
            }, cookieOptions); 

```

Is this the correct way? Do I have to setup MixedAuth for my page in a different Way? 

Regards Dumitru

**Comment by MohammadYounes** [comment]
Hi,


No need to modify the path, it will be [auto resolved](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthHandler.cs#L198-L202) to include your application base path.


Most probably, you don't have the windows authentication section unlocked as described in the [README](https://github.com/MohammadYounes/OWIN-MixedAuth#iis) which might cause a 500 error.

Thanks.

**Comment by meister-d** [comment]
Hi Mohammad,
thanx for your reply. You were right. I changed the  IIS Express Configuration to 

```xml
<section name="windowsAuthentication" overrideModeDefault="Allow" />
```

Now it works.

Regards Dumitru
