### ISSUE TITLE
Register windows users from backend

### ISSUE THREAD

**Issue by ajimr** [MohammadYounes/OWIN-MixedAuth#58]
Mohammad,

How do I register windows users from backend, since my scenario admin will register/create users from his machine (which he logged-in using his credential) using user console modules.

Advance thanks

**Comment by MohammadYounes** [comment]
You can use `UserManager` to create local users account. Then, for each account add an external login matching the windows user account:

| loginProvider | providerKey |
| --- | --- |
| Windows | Windows User SID |

**Comment by ajimr** [comment]
Thanks Mohammad
