### ISSUE TITLE
Custom Claims not available

### ISSUE THREAD

**Issue by Hainesy** [MohammadYounes/OWIN-MixedAuth#60]
I'm following your example of how to add custom claims from the windows login. I can confirm the below code is correctly returning a claim:

```
app.UseMixedAuth(new MixedAuthOptions
{
    Provider = new MixedAuthProvider
    {
        OnImportClaims = identity =>
        {
            var claims = new List<Claim>();

            using (var principalContext = new PrincipalContext(ContextType.Machine)) // todo: Change to ContextType.Domain  ?
            {
                using (var userPrincipal = UserPrincipal.FindByIdentity(principalContext, identity.Name))
                {
                    if (userPrincipal != null)
                    {
                        claims.Add(new Claim(ClaimTypes.WindowsAccountName, userPrincipal.Name ?? string.Empty));
                        claims.Add(new Claim(ClaimTypes.Email, userPrincipal.EmailAddress ?? string.Empty));
                        claims.Add(new Claim(CustomClaimTypes.DisplayName, userPrincipal.DisplayName ?? userPrincipal.Name ?? string.Empty));
                    }
                }
            }
            return claims;
        }
    }

}, cookieOptions);
```

Debugging reveals that DisplayName is being correctly set, however when I try to access this value in the view with `@ClaimsPrincipal.Current.FindFirst(CustomClaimTypes.DisplayName)?.Value` I get an empty string.

Am I missing another step that will correctly include the claims?

**Comment by MohammadYounes** [comment]
Imported claims will be added to the claims list of the external identity (windows identity, Not the local identity). 

Upon user registration or account linking you need to read those claims from the external identity and save them to the database as part of the local identity claims.
