### ISSUE TITLE
Automatic redirect

### ISSUE THREAD

**Issue by lneninger** [MohammadYounes/OWIN-MixedAuth#61]
When I call the externallogin I receive several automatic redirects. The Action in the Api Controller is never reached 

response
![capture](https://cloud.githubusercontent.com/assets/6623279/24028425/35b8fdc6-0aa5-11e7-8b90-4b32525cf4be.PNG)

cookieOptions
           var cookieOptions = new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/Login"),
                Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user logs in.
                    // This is a security feature which is used when you change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, AbstractUser>(
                        validateInterval: TimeSpan.FromMinutes(30),
                        regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
                }
            };

I have no clue where the problem is.

**Comment by MohammadYounes** [comment]
You need to enable anonymous authentication to allow unauthorized access to the login page.

**Comment by lneninger** [comment]
Fix activating anonomous authetication

**Comment by lneninger** [comment]
Thanks!!!
