### ISSUE TITLE
Restrict to set of windows users

### ISSUE THREAD

**Issue by last-Programmer** [MohammadYounes/OWIN-MixedAuth#63]
Hi,
With windows authentication i would like to restrict to set of windows users? Could you please let me know How to redirect to login page when the windows users belong to restricted windows user which i will load from a data store.

Thanks

**Comment by MohammadYounes** [comment]
Hi,

See answer to a similar question [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/56#issuecomment-268233891).

Thanks!

**Comment by last-Programmer** [comment]
HI,

Thank you for the reply. But i am not using the asp.net identity manager for authentication. I am using simple authentication like [https://www.codeproject.com/tips/849113/four-easy-steps-to-set-up-owin-for-form-authentica](url) and referencing your windows authentication dll. not sure how to do it if i only use your dll and not asp.net authentication methods.

**Comment by MohammadYounes** [comment]
In theory it should be the same, restrict the users on Sign In. However, I read through the link you referenced and there is no mention of how/when to Sign In an external identity?

**Comment by last-Programmer** [comment]
Thank you.

here is the sample project which i am using. Please let me know how i can do it here. Thanks

[OWINAuth.zip](https://github.com/MohammadYounes/OWIN-MixedAuth/files/936967/OWINAuth.zip)

**Comment by MohammadYounes** [comment]
Looking at the project you provided, It's very basic and does not seem to support OWIN Authentication providers. I recommend to switching to asp.net default project template.

Thanks.

**Comment by last-Programmer** [comment]
Thank you for your suggestion. But we want to use basic forms and Windows authentication only. We don't need the asp.net providers. At present we just use forms authentication but we want to migrate to owin simple owin forms authentication against our existing data store ( we don't need to add additional claims except nam). And also saw ur Windows authentication with owin and it is an additional solution for us which we would like to integrate. It would be helpful if you could give a hint about  where we can add additional restriction for Windows users check.

Thank you

**Comment by MohammadYounes** [comment]
As I mentioned earlier, the easiest way is to incorporate such logic just before issuing the authentication cookie. 

Since you already included OWIN, It will be much simpler to use its authentication providers.

**Comment by last-Programmer** [comment]
Hi,

I managed to do it. It seems to be working fine with Google Chrome and IE. But Microsoft Edge and FIrefox browsers are displaying Authentication dialog for user Windows User name and password. Is this an expected behavior in these browsers?

Thank You

**Comment by last-Programmer** [comment]
Hey Sorry i do did a bit search on this and found this firefox
https://liquidstate.net/enabling-ntlm-authentication-single-sign-on-in-firefox/
and it works.

But it seems to be that for Microsoft edge it is by design. Correct me if i am wrong..

Thank You

**Comment by MohammadYounes** [comment]
Yes, It seems to be [by desgin](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4776775/).
