### ISSUE TITLE
Allow seamless logon for authenticated Windows users

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#64]
Hi and thank you, Mohammad, for this great library! I've downloaded your sample app and got it working on my localhost. A few questions:

- I don't need to have the Windows authenticated users assign/store their username on the database; I will fetch it using their login ID from a custom table on the database. Is it possible to disable this for Windows auth users?
- My usage scenario is this: If the user is authenticated against Windows, let them in; else take the user to the logon page. So the logon is seamless for successful Windows authenticated users (no logon screen, even for the first time). These users don't need a "log off" button/link. How do you do this?

Thank you again for this amazing library, Mohammad :)

**Comment by MohammadYounes** [comment]
For automatic windows login, Follow the steps in  https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443. 

As for fetching the login ID from a custom table, you'll need to hook in to where the external identity is signed in and do your own logic there. For example, Account Controller [`ExternalLoginCallback`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L328).

Let me know if you need further assistance.

Thanks!

**Comment by arc95** [comment]
Thanks, @MohammadYounes! I'll work on it. You're quick :)

**Comment by arc95** [comment]
A follow-up: Is there a way to fetch the user's AD roles after they're authenticated on Windows? I need to limit the app to a few AD groups. Thanks.
