### ISSUE TITLE
Determining if user is internal/external

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#66]
Hi @MohammadYounes. Working on implementing the auto login for Windows users. Would I need to also add this code to make it work?  [change to RegisterMixedAuth()](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-76956157) 

I'm getting a `Server Error in '/' Application. Object reference not set to an instance of an object.` when I launch the MVC5-MixedAuth with the changes indicated [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443).

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Microsoft.Owin.Security.Cookies.<AuthenticateCoreAsync>d__0.MoveNext() +324
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<BaseInitializeAsync>d__2.MoveNext() +616
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +255
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

Thanks.

**Comment by MohammadYounes** [comment]
Hi,

No, that check will be based on IP address to decide whether to send the challenge or not.

The steps mentioned in the comment are to enable Auto Windows Login, try clearing your cookies and run the application again.

Thanks.

**Comment by arc95** [comment]
Thanks, @MohammadYounes. Should I be doing these changes in the MVC5-MixedAuth or OWIN-MixedAuth solutions?

**Comment by MohammadYounes** [comment]
These are for OWIN-MixedAuth.

**Comment by arc95** [comment]
OK, I added these changes to a fresh copy of the app. But it loads the home page with the "Register" + "Log in" links at top. When I click Log in, it redirects to /Account/Login and shows two log in methods. I was hoping that when the user loads the app in the browser, it would already know they're on the AD. Am I missing something?

**Comment by arc95** [comment]
@MohammadYounes , thanks. Tried it with clearing the cookies and [those 4 changes](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443) on a fresh copy of OWIN-MixedAuth. It's not behaving the way I expected: It still loads the home page, and I have to click Log in, then click Windows button. With these changes, is it supposed to automatically know who the user is on the AD?
