### ISSUE TITLE
Auto sign on for Windows users

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#67]
I tried it with clearing the cookies and [these 4 changes](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443) on a fresh copy of OWIN-MixedAuth. It's not behaving the way I expected: It still loads the home page, and I have to click Log in, then click Windows button. With these changes, is it supposed to automatically know who the user is on the AD?

**Comment by MohammadYounes** [comment]
Does the home page require authentication ? Try hitting a page that requires authentication, and you should be challenged to authenticate using your windows credentials.

**Comment by arc95** [comment]
Hmm, it seems to be working! I put `[Authorize]` attribute on the HomeController/About action and when I try going there, it pulls my name from the db and displays it at the top. Woohoo! Thanks, @MohammadYounes :+1:

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
