### ISSUE TITLE
Equivalent of ExternalLoginCallback for Forms Auth?

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#68]
Hi. Is there an equivalent to the callback `ExternalLoginCallback` function for Forms Auth that we can trigger after Account/Login action returns success? I stepped through that function and noticed that `HttpContext.User.Identity` isn't set until we redirect to another action. Thanks.

**Comment by MohammadYounes** [comment]
Hi,

I am afraid I don't understand the question, can you elaborate ?

**Comment by arc95** [comment]
@MohammadYounes thanks for your reply. Sorry for my confusing question. Here's what I need to do: after a user is authenticated via Forms Authentication, before they access any pages, I'd like to fetch some details about them from the database. Is AccountController/Login where I would do this? With Windows Auth I can use ExternalLoginCallback, but  for Forms Auth that doesn't seem to get called.

**Comment by MohammadYounes** [comment]
Yes, The [`ExternalLoginCallback`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L326) is used to sign the user in using the external identity. While [`Login`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L67) will sign the user in using Username/Password.

**Comment by arc95** [comment]
@MohammadYounes thank you. A follow up: what object would contain the user's identity information after successful authentication in Login action? I stepped through Login and noticed HttpContext.User.Identity didn't seem to be populated until after it redirected to another action. I'd like to set some roles on the user via Claims.

**Comment by MohammadYounes** [comment]
Claims can be added through the [`SignInManager`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/App_Start/IdentityConfig.cs#L92) when the claims identity is [generated](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Models/IdentityModels.cs#L12).

**Comment by arc95** [comment]
@MohammadYounes thank you for all your help! You've written an amazing library, plus you take time out of your day to help people. Very impressive!
