### ISSUE TITLE
Determine which type of authentication is being used

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#69]
Hi @MohammadYounes . Is there a way in the `GenerateUserIdentityAsync()` method to determine if user is authenticating via Windows or Forms? Thanks.

**Comment by MohammadYounes** [comment]
Hi,

It's possible, but it would involve a lot of overrides. 

However,  you can determine if the user has a linked Windows account or not by checking `this.Logins`.

Thanks.

**Comment by arc95** [comment]
Perfect, @MohammadYounes! That does the trick very nicely :+1:

**Comment by arc95** [comment]
@MohammadYounes, is it possible to add the user's AD groups -- `ClaimTypes.GroupSid` -- as claims to the `ClaimsIdentity` object in `GenerateUserIdentityAsync()` method? I can see them in `ExternalLoginCallback()` but not in `GenerateUserIdentityAsync()`. Thank you.

**Comment by MohammadYounes** [comment]
The best place to import AD groups is when importing custom claims as mentioned in the [README](https://github.com/MohammadYounes/OWIN-MixedAuth#importing-custom-claims). 

What do you mean by you can see them in `ExternalLoginCallback` ?

**Comment by arc95** [comment]
Thanks, @MohammadYounes. When I put a breakpoint in `ExternalLoginCallback`, I can run this code to fetch the user's AD groups and try to set them as roles on the user:

```
var identity = HttpContext.Request.LogonUserIdentity;
var roles = identity?.Claims
		   .Where(c => c.Type == ClaimTypes.GroupSid)
		   .Select(c => c.Value)
		   .ToList();
var roleList = new List<Claim>();
foreach (var group in roles)
{
	roleList.Add(new Claim(ClaimTypes.Role, GetGroupNameBySid(group)));
}
identity?.AddClaims(roleList);
```

Here's the helper method that fetches the user-friendly group name from the AD:

```
public static string GetGroupNameBySid(string sid)
{
	PrincipalContext ctx = new PrincipalContext(ContextType.Domain);
	GroupPrincipal group = GroupPrincipal.FindByIdentity(ctx, IdentityType.Sid, sid);
	return group.SamAccountName;
}
```

I'm able to see some 37 AD groups that my login belongs to, but the adding I do here doesn't seem to affect the User object.

But as you indicated, `app.UseMixedAuth()` is a better place for it; I can fetch the groups from `HttpContext.Current.Request`.

**Comment by MohammadYounes** [comment]
> but the adding I do here doesn't seem to affect the User object.

The `SignInManager` will add the claims stored in the database. 

Also note that when importing claims inside `MixedAuthProvider`, Imported claims will be added to the claims list of the external identity (windows identity, Not the local identity). 

Thus, You should save the imported claims to the database upon user registration or account linking.

*See* #60, #49 and #45
