### ISSUE TITLE
Sign out Windows user

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#70]
Hi @MohammadYounes. In `ExternalLoginCallback`, I'm checking to see if the user is in some groups; if not, I want to sign them out. I've got this code:

```
if (!identity.HasAnyClaim(GetAllowedRoles()))
{
	AuthenticationManager.SignOut();
	return RedirectToAction("Index", "Home");
}
```

When redirected, the username is showing at the top still; I was hoping it would be cleared out. What am I doing wrong? Thanks.

**Comment by MohammadYounes** [comment]
If you are using Auto Windows login and your home page requires authentication, you'll be automatically signed in again. 

See #4 and #15

**Comment by arc95** [comment]
Thanks, @MohammadYounes. There's no authentication on the Home/Index page.

From what I've been reading, it's much more difficult to log someone out of Windows auth: https://stackoverflow.com/a/1067362/177416

**Comment by arc95** [comment]
@MohammadYounes: found a solution. I fetch the username from loginInfo and remove my domain stuff from the string. Then I pass it to this:

```
        private List<string> GetGroups(string userName)
        {
            List<string> result = new List<string>();
            WindowsIdentity wi = new WindowsIdentity(userName);

            foreach (IdentityReference group in wi.Groups)
            {
                try
                {
                    result.Add(group.Translate(typeof(NTAccount)).ToString());
                }
                catch (Exception ex) { }
            }
            result.Sort();
            return result;
        }
```

This fetches the user's domain groups; I then check to ensure the user is in the groups I want **before** running `SignInManager.ExternalSignInAsync()`, which creates the authentication token. If the user isn't in the groups, I simply RedirectToAction("Login") and don't have any cookie to worry about :)

**Comment by MohammadYounes** [comment]
Can you share the complete modified code of `ExternalLoginCallback` ?

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
