### ISSUE TITLE
Can't log in - 404 error

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#71]
Hi @MohammadYounes. I'm now implementing OWIN-MixedAuth in the main app, having tested it on its own. I've implemented all the changes for seamless Windows authentication for the user. However, it's giving me this error when I try to go to the home page. Any thoughts on what could be causing this? It's like it's caught in some loop.

This is the error:

```
Server Error

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
```

And this is what the URL looks like:

`http://localhost:54071/APPS/MYAPP/Account/WindowsLogin?ReturnUrl=%2FAPPS%2FMYAPP%2FAccount%2FWindowsLogin%3FReturnUrl%3D%252FAPPS%252FMYAPP%252FAccount%252FWindowsLogin%253FReturnUrl%253D%25252FAPPS%25252FMYAPP%25252FAccount%25252FWindowsLogin%25253FReturnUrl%25253D%2525252FAPPS%2525252FMYAPP%2525252FAccount%2525252FWindowsLogin%2525253FReturnUrl%2525253D%252525252FAPPS%252525252FMYAPP%252525252FAccount%252525252FWindowsLogin%252525253FReturnUrl%252525253D%25252525252FAPPS%25252525252FMYAPP%25252525252FAccount%25252525252FWindowsLogin%25252525253FReturnUrl%25252525253D%2525252525252FAPPS%2525252525252FMYAPP%2525252525252FAccount%2525252525252FWindowsLogin%2525252525253FReturnUrl%2525252525253D%252525252525252FAPPS%252525252525252FMYAPP%252525252525252FAccount%252525252525252FWindowsLogin%252525252525253FReturnUrl%252525252525253D%25252525252525252FAPPS%25252525252525252FMYAPP%25252525252525252FAccount%25252525252525252FWindowsLogin%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252FAPPS%2525252525252525252FMYAPP%2525252525252525252FAccount%2525252525252525252FWindowsLogin%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252FAPPS%252525252525252525252FMYAPP%252525252525252525252FAccount%252525252525252525252FWindowsLogin%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252FAPPS%25252525252525252525252FMYAPP%25252525252525252525252FAccount%25252525252525252525252FWindowsLogin%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252FAPPS%2525252525252525252525252FMYAPP%2525252525252525252525252FAccount%2525252525252525252525252FWindowsLogin%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252FAPPS%252525252525252525252525252FMYAPP%252525252525252525252525252FAccount%252525252525252525252525252FWindowsLogin%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252FAPPS%25252525252525252525252525252FMYAPP%25252525252525252525252525252FAccount%25252525252525252525252525252FWindowsLogin%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252FAPPS%2525252525252525252525252525252FMYAPP%2525252525252525252525252525252F`

**Comment by MohammadYounes** [comment]
Seems like it can't find the `401.html` from [Step 3](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443), Please check and see if this fixes the issue ?

**Comment by arc95** [comment]
Found the solution: https://stackoverflow.com/a/20454294/177416

```
Highlight the project in Visual Studio
Open the 'Properties' panel on the right (or press F4)
Set 'Windows Authentication' to 'Disabled'
Set 'Anonymous Authentication' to 'Enabled'
```

**Comment by arc95** [comment]
Thanks, @MohammadYounes :) Had to do the above. Just documented for others if they see that bizarre loop on `returnUrl`.

**Comment by MohammadYounes** [comment]
Ah, it's  404.15 error (similar to [#14](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/14)).

Thanks for the feedback!
