### ISSUE TITLE
Location path for enabling mixed auth

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#72]
Hi @MohammadYounes. Following your example from the readme, I've added the following to the Web.config of my main app:

```
<!-- Enable Mixed Auth -->
<location path="MixedAuth">
  <system.webServer>
    <security>
      <authentication>
        <windowsAuthentication enabled="true" />
      </authentication>
    </security>
  </system.webServer>
</location>
```

It's put a blue line under `MixedAuth` and kind of grayed out the whole block: `Location element is unused: no project item found at MixedAuth`. I changed the path to `~` and it seems to be happy, but not sure if that's correct.

What value goes into `path`? Is that the app name? Where do we get the app name? No matter what I put into that, it's getting underlined with a squiggly blue line. Thanks.

**Update:** Thinking path should equal to period "." so it applies to the entire app

**Comment by MohammadYounes** [comment]
Never seen that before! The path corresponds to the MixedAuth end point as defined in [`MixedAuthOptions`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthOptions.cs#L38).

**Comment by arc95** [comment]
I'm going to change it back to MixedAuth; it works that way and everything's happy :)
