### ISSUE TITLE
Auto login without registration for Windows authentication

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#73]
Hi @MohammadYounes. I'm looking at your answer [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-150324984), and trying to change the `ExternalLoginCallback` to not send the user to "ExternalLoginConfirmation" but to the page they were trying to reach originally. In other words, Windows authenticated users shouldn't be taken to the registration page.

Here's my attempt:

```
// Sign in the user with this external login provider if the user already has a login
var result = await SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false);

switch (result)
{
	case SignInStatus.Success:
		return RedirectToLocal(returnUrl);
	case SignInStatus.LockedOut:
		return View("Lockout");
	case SignInStatus.RequiresVerification:
		return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = false });
	case SignInStatus.Failure:
	default:
		return RedirectToLocal(returnUrl);
}
```

The above seems to create an infinite loop. What's the correct way to implement this? 

Also, if the sign-in status is `Failure`, is it okay to have the user fall through to the default case? Thanks.

**Comment by MohammadYounes** [comment]
> if the sign-in status is Failure, is it okay to have the user fall through to the default case?

A **Failure** External sign in status means the user wasn't signed in,  which will redirect you to the login action. Since you have auto login enabled, the app will authenticate your windows account and send you back to `ExternalLoginCallback` and thus the infinite loop.

The windows authentication is just an entry point, That `SignInManager.ExternalSignInAsync`  will translate into a local identity by querying the database for a local account linked to the external `loginInfo`.

If you don't want send windows users to `ExternalLoginConfirmation`, I recommend performing a silent registration to create a local user account and keep asp.net identity flow intact.

**Comment by arc95** [comment]
Thanks, @MohammadYounes, for the explanation on what **Failure** means. (In my life, I have failed in infinite ways! Look up failure in the dictionary, and my picture is there.)

So for the silent registration to create a local account, I'd be running something like this (copied from `ExternalLoginConfirmation`) in `ExternalLoginCallback`. A question: how can I tell in `ExternalLoginCallback` if user has already been silently registered when they logged on another time so I don't try and register them again? Would I run a query against the `User` table and see if this email address exists, if so, not call `UserManager.CreateAsync(user)`?

```
// Get the information about the user from the external login provider
var info = await AuthenticationManager.GetExternalLoginInfoAsync();
if (info == null)
{
	return View("ExternalLoginFailure");
}
var user = new ApplicationUser { UserName = loginInfo.Email, Email = loginInfo.Email };
var result = await UserManager.CreateAsync(user);
if (result.Succeeded)
{
	result = await UserManager.AddLoginAsync(user.Id, info.Login);
	if (result.Succeeded)
	{
		await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
		return RedirectToLocal(returnUrl);
	}
}
	AddErrors(result);
}
```

Thanks again :+1:

**Comment by MohammadYounes** [comment]
> how can I tell in ExternalLoginCallback if user has already been silently registered when they logged on another time so I don't try and register them again? 

Simply use `UserManager` to find the user linked to the external login.

```c#
var user = await UserManager.FindAsync(loginInfo.Login)
if(user == null){
  //register the user
}
```

**Comment by arc95** [comment]
Thank you, @MohammadYounes, for your continued support.

**Comment by arc95** [comment]
Here's the code that worked for me to perform silent registration for Windows users. What do you think, @MohammadYounes? 

```c#
// GET: /Account/ExternalLoginCallback
[AllowAnonymous]
public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
{
	var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
	if (loginInfo == null)
	{
		return RedirectToAction("Login");
	}

	var user = await UserManager.FindAsync(loginInfo.Login);
	if (user == null)
	{
		// Register the user. The user must be added to two tables using the built-in methods.
		var email = loginInfo.DefaultUserName.ToLower().Replace("mydomain\\", "") + "@mydomain.org";  // The email was null on loginInfo, so using the DefaultUserName to build one
		var appUser = new ApplicationUser { UserName = email, Email = email };
		var identityResult = await UserManager.CreateAsync(appUser);  // Adds user to AspNetUsers table
		if (identityResult.Succeeded)
		{
			identityResult = await UserManager.AddLoginAsync(appUser.Id, loginInfo.Login);    // Adds user to AspNetUserLogins
			if (identityResult.Succeeded)
			{
				await SignInManager.SignInAsync(appUser, isPersistent: false, rememberBrowser: false);
				return RedirectToLocal(returnUrl);
			}
		}
	}
	// Sign in the user with this external login provider if the user already has a login
	var result = await SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false);

	switch (result)
	{
		case SignInStatus.Success:
			return RedirectToLocal(returnUrl);
		case SignInStatus.LockedOut:
			return View("Lockout");
		case SignInStatus.RequiresVerification:
			return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = false });
		case SignInStatus.Failure:
		default:		// We'll never hit the below because we're registering Windows users automatically above
			// If the user does not have an account, then prompt the user to create an account
			ViewBag.ReturnUrl = returnUrl;
			ViewBag.LoginProvider = loginInfo.Login.LoginProvider;
			return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = loginInfo.Email });
	}
}

```

**Comment by arc95** [comment]
Also, for those interested in learning more about Windows Identity Foundation, this is a great series of articles: https://docs.microsoft.com/en-us/dotnet/framework/security/

**Comment by MohammadYounes** [comment]
You can simplify it by eliminating the redundant sign in (also not to break the identity flow).

```c#
public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
{
  var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
  if (loginInfo == null)
  {
    return RedirectToAction("Login");
  }

  var user = await UserManager.FindAsync(loginInfo.Login);
  if (user == null)
  {
    // Register the user. The user must be added to two tables using the built-in methods.
    var email = loginInfo.DefaultUserName.ToLower().Replace("mydomain\\", "") + "@mydomain.org";  // The email was null on loginInfo, so using the DefaultUserName to build one
    var appUser = new ApplicationUser { UserName = email, Email = email };
    var identityResult = await UserManager.CreateAsync(appUser);  // Adds user to AspNetUsers table
    if (identityResult.Succeeded)
    {
      identityResult = await UserManager.AddLoginAsync(appUser.Id, loginInfo.Login);    // Adds user to AspNetUserLogins
      if (!identityResult.Succeeded)
      {  
        // do something when linking fails
      }
    } else {
      // do something when registration fails
    }
  }
  // Sign in the user with this external login provider if the user already has a login
  var result = await SignInManager.ExternalSignInAsync(loginInfo, isPersistent: false);

  switch (result)
  {
    case SignInStatus.Success:
      return RedirectToLocal(returnUrl);
    case SignInStatus.LockedOut:
      return View("Lockout");
    case SignInStatus.RequiresVerification:
      return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = false });
    case SignInStatus.Failure:
    default:		// We'll never hit the below because we're registering Windows users automatically above
      // If the user does not have an account, then prompt the user to create an account
      ViewBag.ReturnUrl = returnUrl;
      ViewBag.LoginProvider = loginInfo.Login.LoginProvider;
      return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = loginInfo.Email });
  }
}
```

**Comment by arc95** [comment]
@MohammadYounes thanks! I really like the ELSE's you added, so nothing falls through the cracks. What do you normally do when either registration or linking fails? Log it and redirect to an error page?

By the way, how do you color-code your C# like that? Mine just comes out gray.

**Comment by MohammadYounes** [comment]
> What do you normally do when either registration or linking fails? Log it and redirect to an error page?

Yes, since your normal flow is broken and you may ask the user to try again (in case it was a temporary failure).

> By the way, how do you color-code your C# like that? Mine just comes out gray.

You need to specify the language in your fenced code block, see [creating-and-highlighting-code-blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
