### ISSUE TITLE
Issue when user not in role

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#74]
Hi @MohammadYounes. I added the following to one of my controllers to test what would happen if a user accessed something for which they're not authorized. I'm logging in as a Windows user via seamless authentication:

```c#
[Authorize(Roles = "SomeCrazyRole")
public ActionResult Edit(int id){ ... }
```
The app hourglassed a while, then changed the URL to this:

`http://localhost:54071/APPS/MYAPPS/Account/WindowsLogin?ReturnUrl=%2FAPPS%2FMYAPPS%2FMyController%2FEdit%2F255555`

The page displayed this:

```
localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

It then popped up the challenge dialog box for credentials. I clicked cancel, it then tried to load this page:

`http://localhost:54071/Account/Login`

but threw a 404 error, as that controller and action don't exist at that location. Is this normal behavior? How do I redirect users to an error page if they don't have proper authorization to a controller or action?

**Update:** Would it be wise to check in the `WindowsLogin` action to see if the user is authenticated? If so, redirect them to an error page; the user shouldn't hit this method if they're already authenticated unless they hit a role they don't belong to.

In this scenario, we can use what you described [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-150133039) and run `HttpContext.Request.LogonUserIdentity?.IsAuthenticated` to see if the user is Windows authenticated.

**Comment by MohammadYounes** [comment]
Hello @arc95,

I believe it is better to create a custom authorization attribute based on `AuthorizeAttribute`  and redirect to a custom error view. See this [SO post](https://stackoverflow.com/questions/977071/redirecting-unauthorized-controller-in-asp-net-mvc).

**Comment by arc95** [comment]
Thanks, @MohammadYounes. I added this custom `AuthorizedAttribute` (with help from this [SO post](https://stackoverflow.com/a/5239540/177416)):

```C#
public class AuthorizeRedirect: AuthorizeAttribute
{
	private Constants.Role _roleEnum;

	protected override void HandleUnauthorizedRequest(AuthorizationContext filterContext)
	{
		base.HandleUnauthorizedRequest(filterContext);

		if (filterContext.RequestContext.HttpContext.User.Identity.IsAuthenticated)
		{
			filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new
			{
				action = "Unauthorized",
				controller = "Error",
				sourceAction = filterContext.ActionDescriptor.ActionName,
				sourceController = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName
			}));
		}
	}

	public Constants.Role RoleEnum
	{
		get { return _roleEnum; }
		set {
			_roleEnum = value;
			base.Roles = value.ToString();
		}
	}
}
```

This will pass the source action and controller for logging purposes. I use this custom `AuthorizeAttribute` anytime I need to apply custom roles/users to an object to lock it down. 

Hope this helps others who need similar code. Note also that this requires an `ErrorController` and an `Unauthorized` view. 

**Update:** The above custom `AuthorizeAttribute` has been updated to take enums for the roles and set those to the `base.Role` (based on this [SO post](https://stackoverflow.com/a/44656341/177416)).

The enum can look like this:

```c#
[Flags]
public enum Role
{
	User = 1,
	Finance = 2,
	Management = 4,
	SystemAdmin = 8
}
```

Note the numbering of the above items; this is based on guidance from this [SO post](http://stackoverflow.com/questions/8447/what-does-the-flags-enum-attribute-mean-in-c). The `.ToString()` will produce a comma-separated string of the multiple values -- precisely what `Roles` requires.

To use the custom attribute, 

```c#
[AuthorizeRedirect(RoleEnum = Constants.Role.SystemAdmin | Constants.Role.Management)] 
public class SomeController : Controller
{ ... }

```

**Comment by MohammadYounes** [comment]
Thanks for the feedback!

**Comment by arc95** [comment]
@MohammadYounes, I just updated the code above to reflect some new discoveries. Hope it helps others.
