### ISSUE TITLE
Securing the MixedAuth app

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#75]
Hi @MohammadYounes. I'm adding some [security measures](https://blogs.msdn.microsoft.com/rickandy/2012/03/23/securing-your-asp-net-mvc-4-app-and-the-new-allowanonymous-attribute/) to the mixed auth MVC app. For example, I've added the following to the global filters:

```c#
public static void RegisterGlobalFilters(GlobalFilterCollection filters)
{
	filters.Add(new HandleErrorAttribute());
        filters.Add(new AuthorizeAttribute());
	filters.Add(new RequireHttpsAttribute());
}
```

That global `AuthorizeAttribute` will ensure all controllers/actions are protected; using `[AllowAnnonymous]` will open the login actions to the users. Any other measures you'd recommend?

Also, mixed authentication seems to be discouraged in that linked article. Just wanted to see what your thoughts are as it doesn't really explain the technical reasons. Thanks.

**Comment by MohammadYounes** [comment]
> Any other measures you'd recommend?

The provided article covers a great deal of security measures, and I can't think of anything else at the moment.

> Just wanted to see what your thoughts are as it doesn't really explain the technical reasons.

Up to now I couldn't find any technical explanation of why it's discouraged. May be due to having different authentication flow and how browsers handle them ( for example, credentials caching does not allow actual logout).

However, seems it [might get added to asp.net vNext](https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/4072779-mixed-mode-authentication).

**Comment by arc95** [comment]
Well I saw that post earlier today and added a feature request for your library to be used for adding mixed auth to vNext: https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/19641820-mixed-authentication

**Comment by MohammadYounes** [comment]
I up voted that 😄

**Comment by arc95** [comment]
You've created a solid solution for mixed auth. And you keep answering questions here 😊

**Comment by MohammadYounes** [comment]
Thanks.

**Comment by arc95** [comment]
Hi @MohammadYounes. A follow-up on the global filters: should I be using my custom `AuthorizeRedirect` in the list of filters I add or the default `AuthorizeAttribute`? I basically want to lock everything down. I'll apply `AuthorizeRedirect` manually on some actions that need to be limited to a few roles. Elsewhere, the app has `AllowAnonymous` where users need to access the Login actions.

**Comment by MohammadYounes** [comment]
You should keep using your custom `AuthorizeRedirect`, as it already inherits from `AuthorizeAttribute`. The only difference is you redirect to a view in case the user was already authenticated to prevent going into an infinite loop.
