### ISSUE TITLE
Store additional information on the userIdentity object

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#76]
Hi @MohammadYounes. In `IdentityModels.cs` > `GenerateUserIdentityAsync`, is it possible to store additional information on the `userIdentity` object? It would be great to attach a custom POCO or to have additional read-only properties, which would be available throughout the application while the user is logged on. 

Thanks.

**Comment by MohammadYounes** [comment]
You can do that by adding custom claims.

**Comment by arc95** [comment]
Thanks, @MohammadYounes. Going to implement this tomorrow. A great resource here: https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/how-to-create-a-custom-claim

**Comment by arc95** [comment]
@MohammadYounes, here's the solution I implemented for this, with help from this [SO post](https://stackoverflow.com/questions/44677784/custom-claim-with-boolean-type/),

A class to hold the custom auth types:

```c#
public static class CustomClaimTypes
{
	public static readonly string AuthenticationType = "http://example.com/claims/authenticationtype";
}
```				   
An enum for the auth types:

```c#
public enum AuthenticationType
{
	None = 0,
	Windows = 1,
	Forms = 2
}
```
This code in `IdentityModels.cs` to add the custom claim:

```c#
var isWindows = Logins?.Any(x => x.LoginProvider == "Windows");

var authenticationType = AuthenticationType.None;
authenticationType = (isWindows.GetValueOrDefault(false))
	? AuthenticationType.Windows
	: AuthenticationType.Forms;

userIdentity.AddClaim(new Claim(CustomClaimTypes.AuthenticationType, authenticationType.ToString()));
```
A method in a utilities class to fetch the current auth type from the principal and set it to one of the above enums:

```c#
public static Constants.AuthenticationType GetAuthenticationType()
{
	var authenticationClaimValue = ((ClaimsPrincipal)Thread.CurrentPrincipal)
		.Claims.SingleOrDefault(x => x.Type == CustomClaimTypes.AuthenticationType)?.Value;
	AuthenticationType authenticationType;
	return Enum.TryParse(authenticationClaimValue, out authenticationType) 
		? authenticationType 
		: AuthenticationType.None;
}
```
And finally, a call to get the auth type in an action:

```c#
var authType = Utilities.GetAuthenticationType();
```
