### ISSUE TITLE
Logout button for Forms authenticated users

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#77]
Hi @MohammadYounes. I'm implementing a logout button for the users who are logged in using Forms Auth; the Windows Auth users can't really "log out" unless they close their browser. In addition, the Windows users would never have a Forms account in this app. 

In this scenario, I'm detecting the user's authentication mode in `IdentityModels.cs` and storing it as a custom claim. Then, in the `_LoginPartial.cshtml`, I plan to read that value and show/hide the logout button. 

Is this a good approach? Would it make sense to show a logout button for Windows auth users? 

Thanks.

**Comment by MohammadYounes** [comment]
You may keep it and redirect the user to a view with a message like: `You must close your browser to complete the sign out process`. However, closing a browser tab won't do it, the user must close the browser process completely.

I think it is possible to force the browser to clear the credentials cache by refusing the stored ones several times, I have seen this in Microsoft solutions - such as TFS, where they provide an option to sign in as a different user. 

See this project http://signinas.codeplex.com for a "Sign In As A Different User" implementation.

**Comment by arc95** [comment]
Thanks, @MohammadYounes. I'll look at that. It'll be good to have a true "sign-out" for all users. 

For now, I'm thinking of showing a the message you suggested in a Bootstrap modal for Windows users when they click logout.

**Comment by MohammadYounes** [comment]
@arc95 You should invoke logout action to clear the cookies, the problem with windows users is the browser cache that will log them back in again.

**Comment by arc95** [comment]
@MohammadYounes There's also this solution for forcing logout of Windows users: http://www.morgantechspace.com/2013/08/how-to-force-sign-in-as-different-user.html

For now, I'll have them log out manually via closing of the browser. Version 2.0 of the app can get more fancy :)
