### ISSUE TITLE
AD authentication for users outside of network

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#79]
Hi @MohammadYounes. We've realized a use case scenario for the app: Some users who have AD (Windows) accounts will need to log on from outside of the internal network. As the app is set up right now, it will redirect them to the login page (I think), because it assumes they're Forms Auth users. 

All these users will be having the same domain on their emails (such as "mydomain.org"). Is there a way here to authenticate them against the AD and treat them as Windows authenticated via the Form Auth engine? Would these users pass through `ExternalLoginCallback` and `GenerateUserIdentityAsync`? Other users, those without this domain on their email, will also be using the same Forms Auth page. We can differentiate them based on their email host.

Your help is appreciated because I'm not sure how to implement this. Thanks.

**Comment by MohammadYounes** [comment]
It doesn't matter where do users login from (internal or external network) as long as they have valid AD credentials and IIS can authenticate them.

**Comment by arc95** [comment]
Thanks, @MohammadYounes If they try logging on from outside of the network (from home, let's say), would it pop up a challenge box asking for credentials? Would it do the same for the Forms Auth users?

Sorry for the newbie questions; just trying to wrap my head around this.

**Comment by MohammadYounes** [comment]
>  If they try logging on from outside of the network (from home, let's say), would it pop up a challenge box asking for credentials? 

Yes.

> Would it do the same for the Forms Auth users?

What do you mean ?

**Comment by arc95** [comment]
Do the Forms Auth people not get redirected to the Login page? 

I think I need to implement this on the server and try hitting it from a machine that's not on the AD. Then I can see how it all works. Right now I'm not sure how it will all behave from off the network. Some testing is in order :)

**Comment by MohammadYounes** [comment]
> Do the Forms Auth people not get redirected to the Login page?

All users will be challenged to enter AD credentials, those who don't provide one will have to cancel and get redirected to the login page.

**Comment by arc95** [comment]
@MohammadYounes, thanks. That makes sense, though for Forms Auth users (not on AD), the popup will be confusing. That popup will only authenticate Windows users, and the other folks will have to cancel and go to Login page. Some may try to enter their Forms Auth credentials into that.

**Comment by MohammadYounes** [comment]
You can make a [check based on IP address](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-76956157) to determine if the user is internal or external. Then redirect external users to the login page and provide them with a Windows login option.

**Comment by arc95** [comment]
Brilliant, @MohammadYounes!

**Comment by arc95** [comment]
Hi @MohammadYounes. Follow-up: ~~IP addresses can be spoofed, as I've been reading. So it's not a reliable way to detect who's on the network and who's coming in from outside.~~ 

~~Is there a place in the code where I can tell that the automatic Windows authentication didn't work (as described in the [4 steps here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443)) and **prevent** the challenge popup? I can then redirect them to the login page for Forms Auth. I don't want everyone to see the credentials popup.~~

~~I can also have a page for those with Windows credentials coming in from outside the network; they go to it, click the [Windows] button and it would force the challenge popup. What do you think?~~

**Update:** Just reading about how routers on enterprise networks will prevent someone from spoofing an internal address when coming in from the outside. So using the IP address isn't a big deal for this; the router will reject those trying to come in with an internal IP address.

**Comment by MohammadYounes** [comment]
If someone is spoofing an internal IP address, they should get the internal user experience :)

**Comment by arc95** [comment]
Thanks, @MohammadYounes. I've implemented the code for checking IP address and redirecting, but it doesn't work on localhost, because localhost doesn't show the IP address correctly:

```c#
public static class MixedAuthHelper
{
	private static string GetIPAddress()
	{
		var context = HttpContext.Current;
		var ipAddress = context.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

		if (string.IsNullOrEmpty(ipAddress)) return context.Request.ServerVariables["REMOTE_ADDR"];
		var addresses = ipAddress.Split(',');
		return addresses.Length != 0 ? addresses[0] : context.Request.ServerVariables["REMOTE_ADDR"];
	}

	private static bool IsIPPrivate(string ipAddress)
	{
		var ipParts = ipAddress.Split(new[] { "." }, StringSplitOptions.RemoveEmptyEntries)
								 .Select(int.Parse).ToArray();
		// Limit to 10.x.x.x range.
		return ipParts[0] == 10;
	}

	public static void RegisterMixedAuth(this HttpApplication app)
	{
		app.EndRequest += (object sender, EventArgs e) =>
		{
			if (app.Context.Response.StatusCode == MixedAuthConstants.FakeStatusCode)
			{
				var ipAddress = GetIPAddress();

				var isInternal = (!string.IsNullOrEmpty(ipAddress) && IsIPPrivate(ipAddress));
				if (isInternal)
				{
					//proceed with the challenge
					app.Context.Response.StatusCode = 401;
					app.Context.Response.SubStatusCode = 2;
				}
				else
				{
					//redirect to login page.
					app.Context.Response.StatusCode = 302;
					app.Context.Response.RedirectLocation = "/Account/Login";
				}
			}
		};
	}
}
```
And I'm calling the above in `Global.asax.cs` like this:

```c#
public MvcApplication()
{
	this.RegisterMixedAuth();
}
```

This code works on the server. Is there any way to fix it to work on localhost? I'm thinking if I could call your `RegisterMixedAuth()` for localhost instead of this, that would fix it. But not sure how. Thanks.

**Comment by MohammadYounes** [comment]
You can try this [SO answer](https://stackoverflow.com/a/20194511/328072).

**Comment by arc95** [comment]
Thanks, @MohammadYounes. Got it working by changing the method we register in `Global.asax.cs`. Still need to test this from outside the network.
```c#
public MvcApplication()
{
        // If not localhost (debugging)...
	if (!System.Diagnostics.Debugger.IsAttached)
	{
		this.RegisterMixedAuthCustom(); // This one redirects on IP address
	}
	else
	{
		this.RegisterMixedAuth(); // This is the default one
	}
}
```
Hope this helps someone else.
