### ISSUE TITLE
Auto login when there are  Windows credentials

### ISSUE THREAD

**Issue by sania13** [MohammadYounes/OWIN-MixedAuth#8]
I understand that in order to get windows principles we need to issue a challenge (401 code) in controller and IIS server would send populated LogonUserIdentity object. I wonder if there is a way to do all that in the Owin middleware pipeline before we get to the MixedAuth middleware for processing. I think it would be more practical to automatically login user when there are Windows credentials (internal users) and present a local login page when there is none (external users).

**Comment by MohammadYounes** [comment]
You can do that by hooking to the application `EndRequest` event, Instead of using the provided [`RegisterMixedAuth()`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/MixedAuthExtensions.cs#L34) extension method, implement your own:
 
```c#
/// <summary>
/// Adds a mixed-authentication middleware support.
/// </summary>
/// <remarks>
/// This is required to enable the modification of the fake status code.
/// </remarks>
/// <param name="app">The HttpApplication instance.</param>
public static void RegisterMixedAuth(this HttpApplication app)
{
    app.EndRequest += (object sender, EventArgs e) =>
    {
        if (app.Context.Response.StatusCode == MixedAuthConstants.FakeStatusCode)
        {
            bool isInternal = myCustomCheckLogic();
            if (isInternal) 
            {
                //proceed with the challenge
                app.Context.Response.StatusCode = 401;
                app.Context.Response.SubStatusCode = 2;
            }
            else
            {
                //redirect to login page.
                context.Response.StatusCode = 302;
                context.Response.RedirectLocation = "/Account/Login";
            }
        }
    }
}
```

Is this what you are trying to accomplish  ?

**Comment by sania13** [comment]
Thank you for your help.

Actually I found what I need. Here what I meant:

------------------------------------------------------------------------------------------
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {

            var loginInfo = AuthenticationManager.GetExternalLoginInfoAsync().Result;

            if (loginInfo == null)
            {
                return new ChallengeResult("Windows", Url.Action("Login", "Account", new { ReturnUrl = returnUrl }));
            }
            else
            {
                return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = loginInfo.Email, Name = loginInfo.DefaultUserName });
            }
        }
--------------------------------------------------------------------------------

Do you think your MixedAuth would work with Identity Server v.3 ? 

It is very cool product. https://github.com/IdentityServer

**Comment by MohammadYounes** [comment]
I haven't used it, But I think yes! 

Thanks for the feedback.

**Comment by emf411** [comment]
Hello,

I am using the code you suggested above by creating my own hook to the EndRequest event (and registering it in Global.asax), but what else do I need to change so that when a user hits my /Account/Login page, it will automatically log them in if they have valid Windows credentials?

Thank you!

**Comment by MohammadYounes** [comment]
@emf411 This is different, If your target is to have auto windows login as described in the MVC5-MixedAuth solution, You could do the following:

**1. Startup.Auth.cs**: Change `LoginPath` to point to Windows Login Action

```C#
LoginPath = new PathString("/Account/WindowsLogin"),
```

**2. AccountController.cs**: Add `WindowsLogin` action to request the windows challenge.

```C#
[AllowAnonymous]
public ActionResult WindowsLogin(string returnUrl)
{
    return new ChallengeResult("Windows", Url.Action("ExternalLoginCallback", "Account", new { ReturnUrl = returnUrl }));
}
```

**3. 401.html**: Add 401.html error page to your app root that will redirect to the normal login page:
```HTML
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <!-- redirect to normal login page -->
    <meta http-equiv="refresh" content="0;URL='/Account/Login'" />
</head>
<body>
    Invalid credentials, redirecting ...
</body>
</html>
```


**3. Web.config**:  Use 401.html to respond to 401 HTTP error (in case of login failure): 

```XML
<system.webServer>
    <httpErrors errorMode="Custom">
      <remove statusCode="401"/>
      <error statusCode="401" path="401.html" responseMode="File" />        
    </httpErrors>
</system.webServer>
```

Thanks!

**Comment by emf411** [comment]
This is perfect, thank you so much!!  I figured out a likely inefficient work-around, your WindowsLogin function was exactly what I needed.  Code is now working as expected, Windows users in my database are automatically being logged in, and non-Windows users are getting to the Login page.

Thanks very much for the quick reply to this!

**Comment by emf411** [comment]
One more question around the ExternalLoginCallback method.

I deleted a Windows user account from my AspNetUsers table which is correctly causing  SignInManager.ExternalSignInAsync to return SignInStatus.Failure

I am correctly returned to /Account/Login at this point.  Locally on IIS Express, everything runs as expected, however my Windows 2008 IIS is incorrectly storing that Request.IsAuthenticated is True, and User.Identity.GetUsername() is displaying the Windows username.

Do you know how I can clear out the User.Identity model when the SignInStatus.Failure occurs, so that there is no Username displaying, and the "Log Off" link is also not displaying?

Thank you!

**Comment by MohammadYounes** [comment]
`Request.IsAuthenticated` will be True when the user has been authenticated (for example: by a cookie), while `Request.LogonUserIdentity.IsAuthenticated` will be True when the Windows user has been authenticated.

Clear your cookies and try again!

**Comment by emf411** [comment]
Thank you Mohammad!  I really appreciate your help on this.

I tried clearing cookies but I'm still having the same problem.

Maybe my scenario is slightly different.  My site will be both internal on my LAN and external to the Internet.  What I'm trying to do is this:

1. When the user hits my site, determine if they are internal or external (I already have this working)

2. If they are external, send them to /Account/Login

3. If they are internal, grab their Windows credentials and run the ExternalCallBack method to make sure they are in my database

4. If they are not in my database, return them to /Account/Login and make sure that the AuthenticationManager has signed them out so the Login page doesn't display their Windows username when I call User.Identity.GetUsername()

Step 4 seems to be where I am stuck, even if I try AuthenticationManager.SignOut() I am still seeing that the User.Identity model has not been cleared.

**Comment by MohammadYounes** [comment]
Seems you have a specific scenario, but all can be managed in your actions. In step 4, you may also need to sign out the external cookie  `AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);`.

As for not registering those users, it's controllable in your [`ExternalLoginCallback`](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.cs#L206-L218) (don't send them to External Login Confirmation).

**Comment by MrHmP** [comment]
Hi @MohammadYounes , thanks for your help of this question. I have one doubt regarding this.
I already have a custom error 401 page, so I cant redirect user to `/Account/Login` .

Is there any other alternate?
Thankyou for your time.

**Comment by MohammadYounes** [comment]
Hello @MrHmP 

Unfortunately, I have no other alternative at the moment.

Thanks!

**Comment by sylfree9999** [comment]
Hi @MohammadYounes 

I have tried what you suggested [above](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443) in the MVC project. But for some reason, the page did not redirect to the windowslogin. It just went straight to the login page. What did I miss here? Could you please help?

Many thanks!
[MVC.zip](https://github.com/MohammadYounes/OWIN-MixedAuth/files/1887192/MVC.zip)

**Comment by MohammadYounes** [comment]
Hello @sylfree9999 

Did you try checking the network tab to see the sequence of requests ? Also, Did you unlock the `windowsAuthentication` section as mentioned [here](https://github.com/MohammadYounes/OWIN-MixedAuth#iis-express) ?

**Comment by sylfree9999** [comment]
Hi @MohammadYounes , yes, I have unlock that in the .vs config and actually I am able to login using windows domain account. But I still could not **auto** login the domain user since the application went straight to login action instead of winlogin. 
![loginnetwork](https://user-images.githubusercontent.com/15099465/38549516-c0795356-3ce6-11e8-8781-73e557d160d8.PNG)

**Comment by MohammadYounes** [comment]
@sylfree9999 FormsAuthentication module should be [removed](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Web.config#L35-L39) from the whole app, not just MixedAuth [path](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Web.config#L26-L34).
