### ISSUE TITLE
Why does "Windows - Authentication" need to be set to Read/Write?

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#80]
Hi @MohammadYounes. For the setting on the full IIS to allow MixedAuth, why do we need to change "Windows - Authentication" to Read/Write in Feature Delegation? What does this setting do? I'm writing a request to our server admins and need to provide them with a justification. 

Read about it [here](https://docs.microsoft.com/en-us/iis/manage/managing-your-configuration-settings/an-overview-of-feature-delegation-in-iis), but it doesn't explain how it applies to our usage. More details [here](https://technet.microsoft.com/en-us/library/hh831543(v=ws.11).aspx):

> When you select Read/Write for a feature, you unlock the feature's related configuration sections in the server-level configuration file. Configuration changes for that feature will then be read from and written to Web.config files in sites or applications.
> 
> Additionally, configuring a feature to be Read/Write enables nonadministrative users to see and configure the feature in IIS Manager for sites or applications to which they are allowed to connect.

 Thanks.

**Comment by MohammadYounes** [comment]
> why do we need to change "Windows - Authentication" to Read/Write in Feature Delegation? What does this setting do?

As mentioned in the README:

> **Important!** Enabling windows authentication for a sub path requires `windowsAuthentication` section to be unlocked at a parent level.

This is to allow setting windows authentication on a sub path and not the entire app. In essence, the app is using Forms Authentication and only `MixedAuth` endpoint is using the Windows Integrated Authentication.

**Comment by arc95** [comment]
Great explanation, @MohammadYounes. Thanks!
