### ISSUE TITLE
Logging errors originating within /MixedAuth

### ISSUE THREAD

**Issue by Wyrus** [MohammadYounes/OWIN-MixedAuth#84]
I have a few users with various browsers getting occasional login errors when using windows auth. I don't have any reliable error information from them - they're users. :) 
I have an Application_Error handler in my global.asax, and it receives errors and does appropriate logging when the errors originate from my app.
However, errors from the MixedAuth code aren't tripping my error handler. If I understand what's going on, the /MixedAuth sub-path has a completely independent handler, so my App_Error method won't get called. 

For example - If my code has a db connection problem, App_Error gets it. If the Identity stuff in MixedAuth has a db problem - I see the yellow error page.

I'm having a hard time nailing down the "why" since I can't get reliable and sufficiently detailed error reports. So, what is a reasonable place to trap (and log) errors originating from within /MixedAuth? 

My app is using MVC5. For the /MixedAuth path, WindowsAuth is enabled and NTLM is moved ahead of Negotiate.

FWIW - Everything is working great for most installations. There's just those few outliers that are driving me crazy.

Thanks!

**Comment by MohammadYounes** [comment]
You may try adding an OWIN exception handler middle ware . Something like [this project](https://github.com/timReynolds/WebApiExceptionDemo).

**Comment by Wyrus** [comment]
Thanks for the info. Your suggestion worked out great.

As with most of .NET, at least half the battle is knowing what is possible. ☺

Scott Williams
EnerSys Corporation

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
