### ISSUE TITLE
Users authenticated through windows auth randomly using Windows Identity

### ISSUE THREAD

**Issue by jbenzshawel** [MohammadYounes/OWIN-MixedAuth#85]
For users who have authenticated as a windows user they end up having both a Claims Identity and a Windows Identity. While using the application the Windows Identity is randomly lost and the User.Identity only has the Claims Identity. In some cases after losing the Windows Identity on next page the user will have both the Windows and Claims Identities again. In other cases just the Claims Identity exists in the User.Identity. 

Do you have any ideas around what could be causing this? In our testing it appears to be random. 

After a user has been authenticated is there a way to get rid of the Windows Identity and just use the Claims Identity?

**Comment by MohammadYounes** [comment]
I haven't experienced such issue, The Windows Identity is supposed to be available when authenticating against the MixedAuth endpoint, after that you'll have the claims identity only.

Did you enable Windows Authentication to the whole app or just the endpoint as described in the [README](https://github.com/MohammadYounes/OWIN-MixedAuth#iis) ? Also, does this Windows Identity match the logged in user account or the IIS service account ? And what's the Windows Identity authentication type  ?

**Comment by jbenzshawel** [comment]
Thanks for the response. I believe Windows Authentication is enabled for the whole app as the web.config setting is like the README: 

```xml
<!-- Enable Mixed Auth -->
<location path="MixedAuth">
  <system.webServer>
    <security>
      <authentication>
        <windowsAuthentication enabled="true" />
      </authentication>
    </security>
  </system.webServer>
</location>
```

The Windows Identity matches the login user and the authentication type is negotiate: 
```
System.Web.HttpContext.Current.User.Identity
{System.Security.Principal.WindowsIdentity}
    AccessToken: {Microsoft.Win32.SafeHandles.SafeAccessTokenHandle}
    Actor: null
    AuthenticationType: "Negotiate"
    BootstrapContext: null
    Claims: {System.Security.Principal.WindowsIdentity.<get_Claims>d__95}
    CustomSerializationData: null
    DeviceClaims: Count = 0
    Groups: {System.Security.Principal.IdentityReferenceCollection}
    ImpersonationLevel: Impersonation
    IsAnonymous: false
    IsAuthenticated: true
    IsGuest: false
    IsSystem: false
    Label: null
    Name: "WINDOWS_DOMAIN\\JBenzshawel"
    NameClaimType: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    RoleClaimType: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid"
System.Web.HttpContext.Current.User
{System.Security.Claims.ClaimsPrincipal}
    Claims: {System.Security.Claims.ClaimsPrincipal.<get_Claims>d__37}
    CustomSerializationData: null
    Identities: Count = 2
    Identity: {System.Security.Principal.WindowsIdentity}
```

**Comment by MohammadYounes** [comment]
This enables windows authentication for the `MixedAuth` path only.
```xml
<!-- Enable Mixed Auth -->
<location path="MixedAuth">
  <system.webServer>
    <security>
      <authentication>
        <windowsAuthentication enabled="true" />
      </authentication>
    </security>
  </system.webServer>
</location>
```
Make sure the you didn't enable it on [the app or site level](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Web.config#L21).

**Comment by jbenzshawel** [comment]
The authentication mode is set to Forms, but I found another place in the web.config where windowsAuthentication was being enabled which was causing the issue. After that additional setting was removed the Mixed Authentication is behaving as expected.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
