### ISSUE TITLE
Where is the MVC-MixedAuth.mdf file ?

### ISSUE THREAD

**Issue by developer2006** [MohammadYounes/OWIN-MixedAuth#86]
Hello Mohammad,

I can not find MVC-MixedAuth.mdf db file ... where I can I find it or how to generate it?

Thanks,

**Comment by MohammadYounes** [comment]
Hello @developer2006 ,

Running the app will generate the required DB. If you are using IIS instead of IIS Express, change the connection string to use SQLExpress.

Thanks.
