### ISSUE TITLE
Using this solution without the need of a database

### ISSUE THREAD

**Issue by xigolle** [MohammadYounes/OWIN-MixedAuth#88]
Dear Mohammed, 

Really great solution and it works fast and great. 
The only problem I am having with it that it uses/needs a database (and this also creates one).
My question is if this is also possible with only using cookies? 
Because I have been trying a lot of different options but it always uses that database.

Hope you can help me out. 
Thanks in advance! #

**Comment by MohammadYounes** [comment]
@xigolle Yes, it can. Get rid of the `UserManager`  and don't create a `DBContext` - @pcbHikeME did something similar in #35.

**Comment by emcxh35** [comment]
Did you ever get this working - I am looking to do the same
