### ISSUE TITLE
Get E-mail and groups from AD

### ISSUE THREAD

**Issue by lpawlak** [MohammadYounes/OWIN-MixedAuth#9]
After success login I get following message:
>You've successfully authenticated with Windows. Please enter a user name for this site below and click the Register button to finish logging in. 

How to get e-mail address automatic from domain?
And what about AD groups - how to get list of them?

**Comment by MohammadYounes** [comment]
Use [`MixedAuthProvider`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MohammadYounes.Owin.Security.MixedAuth/Provider/MixedAuthProvider.cs)(You can inherit from the existing one or implement your own), In the `GetLogonUserIdentity` method, grab all required info from active directory and add them as claims. For example, the following maps AD groups to role claims:

```C#
private void MapGroupsToRoleClaims(HttpRequestBase request)
{
  foreach (var group in request.LogonUserIdentity.Groups)  
    user.Claims.Add(new IdentityUserClaim()
    {
      ClaimType = ClaimTypes.Role,
      ClaimValue = new SecurityIdentifier(group.Value)
                         .Translate(typeof(NTAccount)).Value
    });
}
```

**Comment by lpawlak** [comment]
Can you explain please where these changes should be in MVC 5 project?

**Comment by MohammadYounes** [comment]
In [**Startup.Auth.cs**](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/App_Start/Startup.Auth.cs#L73) use the overloaded version of `app.UseMixedAuth` method:

```C#
app.UseMixedAuth(new MixedAuthOptions()
{
  Provider = new MixedAuthProvider()
  {
    OnGetLogonUserIdentity = (context) =>
    {  
       var identity = ((System.Web.HttpContextBase)context.Environment["System.Web.HttpContextBase"]).Request.LogonUserIdentity;
       if (identity.IsAuthenticated && identity.FindFirst(ClaimTypes.Email) == null)
       {
         using (var principalContext = new PrincipalContext(ContextType.Domain))
         {  
            using (UserPrincipal userPrincipal = UserPrincipal.FindByIdentity(principalContext, identity.Name))
            {  
               if (userPrincipal != null)
               {  
                  var email = userPrincipal.EmailAddress ?? string.Empty;
                  identity.AddClaim(new Claim(ClaimTypes.Email, email));
                  foreach (var group in userPrincipal.GetGroups())
                      identity.AddClaim(new Claim(ClaimTypes.Role, group.Name));
               }
            }
         }
       }
       return identity;
    }
  }
}, cookieOptions);
```

This will add the user email and AD groups to the claims list of the external identity (windows identity).  

Next you need to read those claims when registering the external user and save them with the local user claims.

**Comment by lpawlak** [comment]
Thank you - it works great!
