### ISSUE TITLE
Windows Security Login appears after domain login

### ISSUE THREAD

**Issue by generik0** [MohammadYounes/OWIN-MixedAuth#90]
Hi

Great package, thanks! Really saved me a lot of trouble combining AD and cookies. Thanks.
Everything seams to work, but after i have added the Mixed Login i get this login modal.
Even though the user / claim is created correctly by the owin middleware and the MixedAuthOptions with the MixedAuthProvider is working and the claim is validated.

Is it some simple user rights or something else? Any ideas, anybody
I am implementing AD SSO mixed with cookies for none AD login. Would be lovely if I can get the last part here to work...

![image](https://user-images.githubusercontent.com/2411563/35286602-bb99a1dc-0060-11e8-877c-ac2fa37ba410.png)

**Comment by generik0** [comment]
I found this stak overflod link that might fix the issue.
https://stackoverflow.com/questions/5402381/receiving-login-prompt-using-integrated-windows-authentication

**Comment by generik0** [comment]
It appears that my responce is being becoming a 401.02 by the MixAuth.
From MixedAuthHandler - InvokeAsync.

The user is either the app ppol user or the IUser (depending on the setup in the IIS.

So it appears that the browser user is not passing it credentials without a login, and hence not SSO.

Any ideas to get the user credentials / auth to pass?
I feel i have tried almost everything.

even:
<authentication mode="Windows" />
<identity impersonate="true" />

**Comment by MohammadYounes** [comment]
Hi,  Did you follow [IIS setup](https://github.com/MohammadYounes/OWIN-MixedAuth#iis)  and [Usage steps](https://github.com/MohammadYounes/OWIN-MixedAuth#usage) mentioned in the README ?

**Comment by generik0** [comment]
Thanks for answering.
I have folmowed work for word... and tjekket multiple times.

**Comment by generik0** [comment]
I am using Ms.Owin 3.1.0 but i dont expect this should make a difference.

Is the MixAuth  supposed to always return 402, and the initial identity always be the iis pool?
Forcing a new request and user credentials from the client?
Is it the client supposed to post its credentials initially?

**Comment by MohammadYounes** [comment]
There are two cases that would cause a 401.2 when hitting the MixedAuth endpoint:

1. User not authenticated 
2. Or already authenticated using cookies (In this case the identity will be the IIS App Pool)

Are you getting the login prompt on every page in your app ?

**Comment by generik0** [comment]
Hi
I am getting the 401.2 because the user is not authenticated.
I integrated the your source into my code and is the user not authenticated that is the issue. The identity is the app pool user which is passing at that point.

After the Authenticator.Callback( ) with the windows provider the MixAutg provider does not get called.
The login prompt appears in the browser.

If I login through the prompt it works from there on in....
But the prompt appears the first time.

Thanks again for your time...

**Comment by MohammadYounes** [comment]
Not sure I understand the exact scenario, is it possible to share a sample project? Do you get the same behavior when running the samples provided in this repo?

**Comment by generik0** [comment]
Good questions, thanks!
I will test more with your project today and get back to you.

It should be noted that we have had som issues with owin, especially with cookies and Nancy togethers with Sessions.
You see, things need to be loaded into owin in the correct order at startup.

Thanks again for your time and the package. I Will get back to you ASAP...

**Comment by generik0** [comment]
I just saw i the readme that MixAuth needs to be registered at PipelineStage.Authenticate

Nancy registers at MapHandler.
So, I guess I did not read the readme well enough. I will look into the PipelineStage when I land at work...

**Comment by generik0** [comment]
So i landed at work, and started digging into it straight away.
The PipelineStage was correct.

I tried your app, and it also came with the credentials.
THen i deleted the Pool and site. IT worked.

I enabled the HTTPS, and the prompt came again..

Could it simply be because the cert is not valid? Then the Sso is not working on HTTPS? or is it only http the mix auth works for?

**Comment by generik0** [comment]
I have tried with a valid cert also now. No cigar :-/
I am at a loss.. And final ideas?

**Comment by generik0** [comment]
Hi Again

I have now tryied on the  customers domain. Where there is a cert and everything for the site.
Interestingly, when i add the url to the internet options/security/Local Intranet then the Sso works...

Hence, i think running locally on the IIS, without a cert appears not to work without login prompt?


LÆets put this in pause until i have deployed the full version to the customer site.

**Comment by generik0** [comment]
I have deployed.
On the customer site it works with https where there is a valid cert and the site needs to be in the intranet zone for default settings to work...

**Comment by MohammadYounes** [comment]
Glad it worked :) and Thanks for the feedback!
