### ISSUE TITLE
Redirect on session timeout

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#91]
Hi @MohammadYounes. How do you deal with session timeouts when using OWIN-MixedAuth? I had put my computer to sleep and came back, clicked a button, and it threw an exception saying it couldn't find that action on the controller. Once I refreshed the page, all was good. I think it's a dead session.

Is there a way to notice that and redirect Windows auth users? For Forms auth users, something like this might work but wondered if you have any experience.

```xml
<authentication mode="None">
	<forms requireSSL="true" loginUrl="~/Account/Login" timeout="1" />
</authentication>
```

**Comment by MohammadYounes** [comment]
@arc95 I don't think this is related to OWIN-MixedAuth. The windows authentication is just an entry point, after that it's all cookies. 

I recommend checking the app again to see what caused the issue.
