### ISSUE TITLE
Challenge popup on some browsers

### ISSUE THREAD

**Issue by arc95** [MohammadYounes/OWIN-MixedAuth#92]
Hi @MohammadYounes. We're getting the challenge popup box on some PCs and with some browsers. For example, Firefox shows the popup when I first load the app, whereas Chrome/IE don't. I've stepped through the code and it all seems to take the same path, whether it's FF or the other browsers. 

Once I enter my credentials, the app is happy. This happens even when hitting servers with good certificates.

**Comment by MohammadYounes** [comment]
Hello @arc95 


 
The prompt depends on **Security Settings/User Authentication** of the current site zone:

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)

**Firefox** has a special flag under `about:config` that you need to enable. Check this [support article](https://support.mozilla.org/en-US/kb/Firefox%20asks%20for%20user%20name%20and%20password%20on%20internal%20sites).


Moreover, Browsers cache the network credentials and use them for subsequent windows authentication requests, **No prompt will be displayed** asking for user credentials (Even if your internet settings were set to prompt for username and password). You need to either close the browser or invalidate the browser credentials cache.


Thanks.

**Comment by arc95** [comment]
Thank you, @MohammadYounes! This worked like a charm. Though the instructions for FF say they may be out-of-date, they still work on the latest FF. As for Chrome, this SO post gives instructions: https://stackoverflow.com/questions/7800938/how-to-enable-auto-logon-user-authentication-for-google-chrome

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
