### ISSUE TITLE
User is not authenticated when we clear the browser history

### ISSUE THREAD

**Issue by nighotatul** [MohammadYounes/OWIN-MixedAuth#93]
Hi Mohammad,
We have implemented OWIN authentication in our module and are successfully implemented for windows authentication in our asp.net web-form application. The strange behaviour happening when we clear history of browser and again login then user is not authenticated and because of user is not authenticated, our application redirect to a login page.

These behaviour only happen when browser history is clear if we not clear the browser history then application running without redirect to login page.

At that time we close the browser and we again clean and rebuild our application and run it again then user is authenticated and we successfully redirect to other page.

Fraemwork-.net Framwork 4.6 and Visual Studio 2017 we used.

**Comment by MohammadYounes** [comment]
Hi @nighotatul 

If clearing browser history includes cookies ? Then yes, your session will be lost and you'll be redirected to login page. 

The windows authentication is just an entry point, after that it's all cookies.


I didn't get that last statement, Do you mean after clearing history you can no longer authenticate unless you rebuild the app ?

> At that time we close the browser and we again clean and rebuild our application and run it again then user is authenticated and we successfully redirect to other page.

**Comment by nighotatul** [comment]
Yes what you mention is correct as after clearing history we no longer authenticate through login page so we close the login page and again clean the solution and rebuild the application and run it again.

**Comment by MohammadYounes** [comment]
The behavior you are describing is an odd one, Can you provide a sample app that I can debug ?
