### ISSUE TITLE
Use with Angular 5 + Webapi

### ISSUE THREAD

**Issue by svesax** [MohammadYounes/OWIN-MixedAuth#94]
Hi Mohammad,
My scenario is 
- A pure Angular5 SPA application (then without MVC support) 
- A separate WebApi application (where I have all my business controller/actions)

I would like to authenticate users with Windows domain or with SQL.
Can I configure your MixedAuth only in Webapi project and use it by call from Angular SPA ?
If yes, what are the order of calls to make from SPA to Webapi (with your module configured) in order to get correct token ?

Thank you very much !!

**Comment by MohammadYounes** [comment]
Hi @svesax,

You can check the SPA example included in this repository. The basic steps are:

1. Enable the application to [use bearer tokens](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L72-L73) to authenticate users. Which requires setting both [Token/Authorization](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L25-L26) endpoints.

2. Before calling any API, you'll need to [get an access token](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L40-L52), By sending the user to:

    1. The [authorize endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L51) for external logins (Windows Login).
    2. The token endpoint  `/token/grant_type=password&username=...&password=...` for username/password flow (Local Forms Login).


3. Finally, send an [authorization header](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/home.viewmodel.js#L14) with your [API calls](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/home.viewmodel.js#L9-L19).


Thanks.

**Comment by svesax** [comment]
Thank you Mohammad but I have always the same problem calling from
Postman:  "error": "invalid_client"
The call I make is this POST
http://localhost:28636/token whith
Content-Type: application/x-www-form-urlencoded
parameters: grant_type=password&username=[USER]&password=[PASSWORD]
But always I get   "invalid_client"
Have I to make some configuration in database or webconfig ?
If I use your pages (SPA Application) all is good (I can authenticate with
forms login), but if I call from a Postman application then I got the error.
I have read someone with the same problem and they suggest  to Override the
ValidateClientAuthentication & GrantResourceOwnerCredentials in the
OAuthAuthorizationServerProvider, but I tried without result...
Thanks a lot for help!

Sveto

2018-03-24 13:10 GMT+01:00 Mohammad Younes <notifications@github.com>:

**Comment by svesax** [comment]
Hi, I have resolved the problem of "/Token" call by
implementing ValidateClientRedirectUri and GrantResourceOwnerCredentials
in ApplicationOAuthProvider.
Now I have (hope) last problem regard windows auth: I can correclty
authenticate with /Account/ExternalLogin, then I call /Account/Authorize
and in the response (302) I see my access_token in Location, but I'm an SPA
the I can not read it...
If you have idea, thanks !

2018-03-24 13:10 GMT+01:00 Mohammad Younes <notifications@github.com>:

**Comment by MohammadYounes** [comment]
@svesax This means you got the token, now just [read](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L43) the hash from [`window.location`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/common.js#L6-L10)

**Comment by svesax** [comment]
Thank you for your help Mohammad, yes is correct what you suggest.
But if I host my UI application in [HOST A] and my WebApi application with
your module in [HOST B], final users will be redirect in [HOST B] with
token in #window.location.hash, then the UI application can not read the
token... this is the problem.
Instead everything works correctly if UI and Webapi (with your module) are
hosted on the same HOST.


2018-03-26 22:52 GMT+02:00 Mohammad Younes <notifications@github.com>:

**Comment by MohammadYounes** [comment]
@svesax Have you tried using  `redirect_uri` ? Another option would be to change the redirect into a response via hooking into application end request event.

```c#
void OnEndRequest(object sender, EventArgs e)
{
  if (Response.StatusCode == 302)
    {
      string location = Response.Headers["Location"];
      int index = location.IndexOf("#access_token");
      if ( index > 0)
      {  
        // rewrite the response ...
```
