### ISSUE TITLE
Trapping 500 error when IIS incorrectly configured

### ISSUE THREAD

**Issue by ghost** [MohammadYounes/OWIN-MixedAuth#95]
Hi,

Is there any way of trapping the 500 server error that occurs when the IIS server is incorrectly configured (Authentication - Windows NOT set to Read/Write in IIS root site feature delegation). I want my application to fall back to forms logon (with an 'incorrectly configured server' error message) when the server is not configured correctly.

Thanks

Chris

**Comment by MohammadYounes** [comment]
Hi Chris, 

This is a server level error, You can only trap it inside [`httpErrors`](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/httperrors/). Might be possible to redirect to a page or action to reconfigure the app:

```xml
<httpErrors errorMode="Custom">
  <remove statusCode="500" subStatusCode="19"/>
  <error statusCode="500" subStatusCode="19" path="fallback.aspx" responseMode="Redirect" />
</httpErrors>
```
Thanks!
