### ISSUE TITLE
mixed auth sso and azur b2c 

### ISSUE THREAD

**Issue by kamranbashir** [MohammadYounes/OWIN-MixedAuth#96]
Salam Younes,

I have a different requirement.

1.On class level i want to use [Authorize] attribute
2. In owin startup i want to have have to type of setup. one azure b2c and second asp.net identity cookie based.

now question is that is that possible and how to setup?

second how to invoke each of them when url is same e.g. www.demoauth.com for both cases.

i feel you might could answer.

thanks

kamran

**Comment by MohammadYounes** [comment]
Salam Kamran,

Can you elaborate more? The requirements are not clear to me.

Thanks.
