### ISSUE TITLE
Can I convert to Windows authentication with Identity?

### ISSUE THREAD

**Issue by zbx888** [MohammadYounes/OWIN-MixedAuth#99]
hi @MohammadYounes. I have one intranet web form application with Identity to authenticate/authorize users in Visual Studio 2015. Now I tried to convert it from "Individual User Account" to Windows authentication to use company AD windows to automatically login if a user click a url. 

Can I use the way you mentioned for user DabPFW in Question #52 https://github.com/MohammadYounes/OWIN-MixedAuth/issues/52). Highly appreciate your guidelines.

**Comment by MohammadYounes** [comment]
@zbx888 This adds windows authentication as an external provider, you need to keep "Individual User Account" then follow the steps to add auto windows login.

Thanks.

**Comment by zbx888** [comment]
hi @MohammadYounes. Thank you so much for your quick response. Really really appreciate.

My question eventually is I want to remove login page and automatically log on the user if a user clicks a URL. It is an intranet web site and every user has a AD account.

Can I still follow the step to change?

**Comment by MohammadYounes** [comment]
Yes, But if all users are under AD, why don't just use windows authentication without using individual user accounts ?

**Comment by zbx888** [comment]
hi @MohammadYounes.  Good morning!
In this intranet application, Not all users are the application users and also we want to use Roles saved in the database table AspNetUserRole to authorize the access.

I followed your steps you recommended
1. Startup.Auth.cs: Change LoginPath to point to Windows Login Action
2. WindowsLogin.aspx.cs: On PageLoad request the windows challenge.
3. 401.html: Add 401.html error page to your app root that will redirect to the normal login page
4. Web.config: Use 401.html to respond to 401 HTTP error (in case of login failure)

Also I changed the Web.Config and project properties to get user's AD UserName by User.Identity.Name
1.     <authentication mode="Windows" />
    <authorization>
      <deny users="?" />
    </authorization>
2. Project Properties
   Anonymouse Authentication =false
   Windows Authentication = true

When I run the application, I got the error  "**404 - File or directory not found**."  and the returnURL over the character limit by repeating again and again.
http://localhost:9797/Account/WindowsLogin.aspx?ReturnUrl=%2FAccount%2FWindowsLogin.aspx%3FReturnUrl%3D%252FAccount%252FWindowsLogin.aspx%253FReturnUrl%253D%25252FAccount%25252FWindowsLogin.aspx%25253FReturnUrl%25253D%2525252FAccount%

**Comment by MohammadYounes** [comment]
@zbx888 Mixed authentication uses cookies and relies on `Windows Authentication` for the MixdAuth endpoint only. You need to enable `Anonymous Authentication` to avoid having the redirect loop (see [this comment](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/14#issuecomment-49452350)).

**Comment by zbx888** [comment]
Even I enabled Anonymous Authentication, still get error 404 - File or directory not found.

The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by MohammadYounes** [comment]
Which file? Can you share the dev tools network log?

**Comment by zbx888** [comment]
@MohammadYounes  Really appreciate your help!!!!
The included is network log file by F12 Developer Tool. Thank you!

[NetworkData.zip](https://github.com/MohammadYounes/OWIN-MixedAuth/files/2442012/NetworkData.zip)

**Comment by zbx888** [comment]
@MohammadYounes Even I enabled the Anonymous Authentication  the redirect URL still keeps loop.

**Comment by MohammadYounes** [comment]
@zbx888 The log is insufficient, as it shows only 1 entry. 

Can you join me here https://gitter.im/MohammadYounes/OWIN-MixedAuth ?

**Comment by zbx888** [comment]
@MohammadYounes  Thank you so much for your invitation but our security policy blocks instant messaging unless special approval.

I will try to build a new one again for testing on my developer computer. Before that please help me confirm that I had to follow the steps mentioned in Readme to configure.
1. On IIS set Authentication-Windows to Read/Write
2. On IIS Express set windowsAuthentication = "Allow" in ApplicationHost file
3. Reference MohammadYounes.Owin.Security.MixedAuth.dll
4. Register MixedAuth in Global.asax
5. Use MixedAuth in Startup.Auth.cs
6. Enable Windows authentication in Web.config

Then 
1.Startup.Auth.cs: Change LoginPath to point to Windows Login Action
2.WindowsLogin.aspx.cs: On PageLoad request the windows challenge.
3.401.html: Add 401.html error page to your app root that will redirect to the normal login page
4.Web.config: Use 401.html to respond to 401 HTTP error (in case of login failure)

BEST REGARDS!

**Comment by MohammadYounes** [comment]
@zbx888 Step 4 - Windows Authentication should be enabled for the `MixedAuth` endpoint only:
```xml
<!-- Enable Mixed Auth -->
<location path="MixedAuth">
  <system.webServer>
    <security>
      <authentication>
        <windowsAuthentication enabled="true" />
      </authentication>
    </security>
  </system.webServer>
</location>
```

**Comment by zbx888** [comment]
hi @MohammadYounes Thank you so much for your help. Finally my application basically is working now. 

I still have two issues so hopefully you can give me further help
1. I set ExpireTimeSpan = TimeSpan.FromMinutes(30) in Startup.Auth.cs
            var cookieOptions = new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/WindowsLogin.aspx"),
                ExpireTimeSpan = TimeSpan.FromMinutes(30),
                Provider = new CookieAuthenticationProvider
                {
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
                        validateInterval: TimeSpan.FromMinutes(20),
                        regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
                }
            };
But I tested it never expires. How to fix it?

2. I try to assign a Role from database for the user by HttpContext.Current.User = new System.Security.Principal.GenericPrincipal(id, myRoles). Which is the best event to assign it? Application_PostAuthenticateRequest or other event?

**Comment by MohammadYounes** [comment]
@zbx888 This behavior is by default. Browsers will cache the windows credentials and use them for subsequent windows authentication requests, no prompt will be displayed asking for user credentials (Even if your internet settings were set to prompt for username and password). You need to either close the browser or invalidate the browser credentials cache.

The log off link will still be required to log the user out. For example, a user logs in using local identity then decides to switch to windows identity.

I think it is possible to force the browser to clear the credentials cache by refusing the stored ones several times, I have seen this in Microsoft solutions - such as TFS, where they provide an option to sign in as a different user.

See this project http://signinas.codeplex.com for a "Sign In As A Different User" implementation.

**Comment by zbx888** [comment]
@MohammadYounes Sorry bother you again and really appreciated your help.
Due to Application pool recycle I use StateServer on same server to keep session data. The current issue is if I keep the application running for several hours or overnight, sometimes got a poping up window for security credential and sometimes not but clicking a link to another page or button to load data got blank page. I checked IIS log file and found that is 401 error.

How to fix this issue?  Thank you so much!

**Comment by MohammadYounes** [comment]
@zbx888 This means your cookie expired due to user inactivity, and clicking a link to another page should redirect you to the auto login end point. What is this blank page you are referring to ?

**Comment by zbx888** [comment]
@MohammadYounes Thank you so much!

YES, the blank page is I refer to.  Because of blank page I only click Back button on the IE browser to auto login.

In IIS log I found 401 error when cookie expired. Why did it not redirect to auto log as set in webconfig:
    <httpErrors errorMode="Custom">
      <remove statusCode="401" />
      <error statusCode="401" path="401.html" responseMode="File" />
    </httpErrors>

If I can check cookie expiration in the Master page, does it work? How do I check the cookie expire in this case.

**Comment by zbx888** [comment]
@MohammadYounes Thank you so much!

YES, the blank page is I refer to. Because of blank page I only click Back button on the IE browser to auto login.

In IIS log I found 401 error when cookie expired. Why did it not redirect to auto log as set in webconfig:
  <system.webServer>
    <httpErrors errorMode="Custom">
      <remove statusCode="401" />
      <error statusCode="401" path="401.html" responseMode="File" />
    </httpErrors>
    <modules>

If I can check cookie expiration in the Master page, does it work? How do I check the cookie expire in this case.

**Comment by zbx888** [comment]
@MohammadYounes Thank you so much.

YES. The blank refers to what is set.
  
I found the 401 error in IIS log when I click the link. How can following setting not work to auto login?
    <httpErrors errorMode="Custom">
      <remove statusCode="401" />
      <error statusCode="401" path="401.html" responseMode="File" />
    </httpErrors>
    <modules>

How do I check cookie expiration in this case?

**Comment by zbx888** [comment]
@MohammadYounes Thank you so much.

YES. The blank refers to what is set.
  
I found the 401 error in IIS log when I click the link. How can following setting httpErrors errorMode="Custom" not work to auto login?
    httpErrors errorMode="Custom"
      remove statusCode="401" 
      error statusCode="401" path="401.html" responseMode="File"
    </httpErrors>

How do I check cookie expiration in this case?

**Comment by zbx888** [comment]
@MohammadYounes Thank you so much from my heart

YES. The blank refers to what is set. Due to blank I only can click BACK button on IE browser to auto login.
  
1. I found the 401 error in IIS log when I click the link getting blank. How can following setting not work to auto login?
    httpErrors errorMode="Custom"
      remove statusCode="401"
      error statusCode="401" path="401.html" responseMode="File"
    httpErrors

2. How do I check cookie expiration in this case so in the function or event I can redirect to login page?

**Comment by zbx888** [comment]
@MohammadYounes Highly appreciated if you can give me some ideas to fix this issue. Thank you.

**Comment by MohammadYounes** [comment]
@zbx888 The 401.html performs the redirect via a meta tag, check if the blank page contains this tag? may be try increasing the number of seconds.

**Comment by zbx888** [comment]
@MohammadYounes Thank you!
Copy the View-> Source On blank page I got following source codes which totally is nothing with my code, looks like system automatically generated and the 401.html not called.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
`<HTML>``<HEAD>`
`<META http-equiv="Content-Type" 
content="text/html; charset=windows-1252">``</HEAD>`
`<BODY>``</BODY>``</HTML>`

**Comment by zbx888** [comment]
@MohammadYounes Thank you !
Got source code from View_Source of the blank page as following and it is generated by system, nothing with my application page which contains Master page. The 401.html file not called and no exception error is caught.

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">`
`<HTML><HEAD>`
`<META http-equiv="Content-Type" 
content="text/html; charset=windows-1252"></HEAD>`
`<BODY></BODY></HTML>`

Very strange!

**Comment by zbx888** [comment]
@MohammadYounes I am still struggle with the application one issue. If you can give some ideas to fix?

s1ppwebdev1 is a testing server name hosting several sites for testing and PayrollReportSSO is my web site folder under which I deployed the application also set StateServer to keep session data for application recycle pool.
 
The application runs fine at first several hours or even overnight on IE after starting then if I click one of links **I got a blank page.** 

I used F12 developer tool to trace the network I found at that moment the page request favicon.ico under server root http://s1ppwebdev1/favicon.ico instead of own application root http://s1ppwebdev1/PayrollReportSSO and HTTP 1.1 404 not found error.

![networksummary0214](https://user-images.githubusercontent.com/39767366/53774779-d5e7f380-3ebd-11e9-9d1c-bb54587b5fe9.PNG)
![requestheader2-0214](https://user-images.githubusercontent.com/39767366/53774784-df715b80-3ebd-11e9-9495-e61e0d269ffe.PNG)
![responseheader2-0214](https://user-images.githubusercontent.com/39767366/53774792-e26c4c00-3ebd-11e9-8e78-b7ec2701aedb.PNG)

Following is working log but when getting a blank page the page didn't finish first step HTTP 302 transfer.

![goodsummary1](https://user-images.githubusercontent.com/39767366/53775051-f95f6e00-3ebe-11e9-9f26-31725d7d2f4d.PNG)

**Comment by MohammadYounes** [comment]
@zbx888 The `favicon.ico` is requested by the browser for each page, if it can't [find it](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_custom_icons_to_your_site) it will try to load it from the root. As you have this deployed as a web application (not a website), the browser is requesting `http://s1ppwebdev1/favicon.ico` instead of `http://s1ppwebdev1/PayrollReportSSO/favicon.ico`.

The logs you shared aren't relevant, as they are not showing any 401's!
